//go:build ignore

// Command htmlentgen generates internal/ops/htmlentity_tables.go from the
// vendored WHATWG named character reference set.
//
// It mirrors CyberChef's own generateHTMLEntities.mjs so that the two stay in
// step: the decode table is every single-code-point, semicolon-terminated spec
// name, and the encode table picks one canonical name per code point using a
// deterministic tiebreak, overridden where a particular historical name is
// preferred.
//
// Run from the repository root:
//
//	go run tools/htmlentgen/gen.go
//
// See tools/htmlentgen/README.md.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"
	"strings"
)

// specEntry is one entry of the WHATWG set: the code points a name stands for.
type specEntry struct {
	CodePoints []int  `json:"codepoints"`
	Characters string `json:"characters"`
}

// isAllUpper reports whether a name is written entirely in capitals, which the
// tiebreak treats as less preferred.
func isAllUpper(s string) bool {
	return s == strings.ToUpper(s) && s != strings.ToLower(s)
}

// canonicalName picks the one name used when encoding a code point: the
// override if there is one, otherwise the deterministic tiebreak — prefer a
// name that is not all capitals, then the shortest, then the alphabetically
// first.
func canonicalName(codePoint int, names []string, overrides map[int]string) string {
	if override, ok := overrides[codePoint]; ok {
		if !contains(names, override) {
			log.Fatalf("override &%s; is not a spec name for code point %d (spec has %v)",
				override, codePoint, names)
		}
		return override
	}
	sorted := append([]string(nil), names...)
	sort.SliceStable(sorted, func(i, j int) bool {
		a, b := sorted[i], sorted[j]
		if ua, ub := isAllUpper(a), isAllUpper(b); ua != ub {
			return !ua
		}
		if len(a) != len(b) {
			return len(a) < len(b)
		}
		return a < b
	})
	return sorted[0]
}

func contains(names []string, want string) bool {
	for _, n := range names {
		if n == want {
			return true
		}
	}
	return false
}

func main() {
	specRaw, err := os.ReadFile("tools/htmlentgen/entity.json")
	if err != nil {
		log.Fatal(err)
	}
	var spec map[string]specEntry
	if err := json.Unmarshal(specRaw, &spec); err != nil {
		log.Fatal(err)
	}

	overrideRaw, err := os.ReadFile("tools/htmlentgen/overrides.json")
	if err != nil {
		log.Fatal(err)
	}
	var overrideStrings map[string]string
	if err := json.Unmarshal(overrideRaw, &overrideStrings); err != nil {
		log.Fatal(err)
	}
	overrides := make(map[int]string, len(overrideStrings))
	for k, v := range overrideStrings {
		cp, err := strconv.Atoi(k)
		if err != nil {
			log.Fatalf("override key %q is not a code point", k)
		}
		overrides[cp] = v
	}

	// Only names written with a trailing semicolon and standing for a single
	// code point can be represented; the spec's 93 multi-code-point names and
	// its 106 legacy semicolon-less forms are left out, as upstream leaves them.
	byCodePoint := map[int][]string{}
	for key, entry := range spec {
		if !strings.HasSuffix(key, ";") || len(entry.CodePoints) != 1 {
			continue
		}
		name := key[1 : len(key)-1] // strip the leading & and trailing ;
		byCodePoint[entry.CodePoints[0]] = append(byCodePoint[entry.CodePoints[0]], name)
	}

	encode := map[int]string{}
	decode := map[string]int{}
	for cp, names := range byCodePoint {
		sort.Strings(names)
		encode[cp] = canonicalName(cp, names, overrides)
		for _, name := range names {
			decode[name] = cp
		}
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by tools/htmlentgen/gen.go; DO NOT EDIT.
//
// HTML entity tables derived from the vendored WHATWG named character
// reference set (https://html.spec.whatwg.org/entities.json), by the same rules
// CyberChef's own generator uses, so the two cannot drift apart.

package ops

// htmlByteToEntity gives the one entity name used when encoding each code
// point (%d of them).
var htmlByteToEntity = map[int]string{
`, len(encode))
	codePoints := make([]int, 0, len(encode))
	for cp := range encode {
		codePoints = append(codePoints, cp)
	}
	sort.Ints(codePoints)
	for _, cp := range codePoints {
		fmt.Fprintf(&b, "\t%d: %s,\n", cp, strconv.Quote(encode[cp]))
	}
	fmt.Fprintf(&b, `}

// htmlEntityToByte maps every spec name to its code point when decoding (%d of
// them), so the names that are not chosen for encoding are still understood.
var htmlEntityToByte = map[string]int{
`, len(decode))
	names := make([]string, 0, len(decode))
	for name := range decode {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "\t%s: %d,\n", strconv.Quote(name), decode[name])
	}
	fmt.Fprint(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile("internal/ops/htmlentity_tables.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote internal/ops/htmlentity_tables.go: %d encode names, %d decode names, %d overrides\n",
		len(encode), len(decode), len(overrides))
}
