package cmd

import (
	"slices"
	"sort"
	"strings"

	"github.com/roberson-io/cchef/internal/core"
)

// maxSummaryLen bounds a derived one-line summary so `cchef list` and command
// help do not wrap in a standard-width terminal.
const maxSummaryLen = 60

// summaryOf returns the concise one-line summary shown for an operation in
// `cchef list` and as its cobra Short. It prefers a curated entry in
// opSummaries and otherwise derives one from the (often multi-sentence)
// CyberChef description.
func summaryOf(meta core.OpMeta) string {
	if s, ok := opSummaries[meta.Name]; ok && s != "" {
		return s
	}
	return deriveSummary(meta.Description)
}

// summaryAbbrevs are lowercase abbreviations whose trailing period must not be
// treated as a sentence boundary when deriving a summary.
var summaryAbbrevs = map[string]bool{
	"e.g": true, "i.e": true, "etc": true, "vs": true, "no": true,
	"approx": true, "incl": true, "al": true,
}

// deriveSummary compresses a description to a single short clause: the first
// sentence, trimmed of its trailing period, truncated at a word boundary with
// an ellipsis if still too long.
func deriveSummary(desc string) string {
	desc = strings.TrimSpace(desc)
	desc = strings.TrimSpace(firstSentence(desc))
	if len(desc) <= maxSummaryLen {
		return desc
	}
	cut := desc[:maxSummaryLen]
	if sp := strings.LastIndex(cut, " "); sp > 0 {
		cut = cut[:sp]
	}
	return strings.TrimRight(cut, " ,;:") + "…"
}

// firstSentence returns s up to the first sentence-terminating ., ! or ? that
// is followed by whitespace (or end of string) and not part of an abbreviation
// such as "e.g.". If none is found it returns all of s.
func firstSentence(s string) string {
	for i := 0; i < len(s); i++ {
		if c := s[i]; c == '.' || c == '!' || c == '?' {
			if i+1 < len(s) && s[i+1] != ' ' && s[i+1] != '\n' && s[i+1] != '\t' {
				continue
			}
			if summaryAbbrevs[strings.ToLower(lastWord(s[:i]))] {
				continue
			}
			return s[:i]
		}
	}
	return s
}

// lastWord returns the trailing run of letters and dots in s (so "up to (e.g"
// yields "e.g"), used to detect abbreviations before a period.
func lastWord(s string) string {
	i := len(s)
	for i > 0 {
		c := s[i-1]
		if (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || c == '.' {
			i--
			continue
		}
		break
	}
	return s[i:]
}

// CyberChef operation categories, used as the values in opCategories and as the
// grouping headings in `cchef list`. Defined as constants so a mistyped category
// is a compile error rather than a silent new group.
const (
	catArithmeticLogic    = "Arithmetic / Logic"
	catCodeTidy           = "Code tidy"
	catCompression        = "Compression"
	catDataFormat         = "Data format"
	catDateTime           = "Date / Time"
	catEncryptionEncoding = "Encryption / Encoding"
	catExtractors         = "Extractors"
	catForensics          = "Forensics"
	catHashing            = "Hashing"
	catLanguage           = "Language"
	catMultimedia         = "Multimedia"
	catNetworking         = "Networking"
	catOther              = "Other"
	catPublicKey          = "Public Key"
	catUtils              = "Utils"
)

// opCategories maps each operation's display name to the CyberChef categories it
// belongs to, mirroring the master table in docs/README.md. It is the source of
// truth for grouping `cchef list`. A few operations (URL Decode/Encode) belong
// to more than one category. TestOpCategoriesMatchRegistry keeps this table in
// exact sync with the registered operations.
var opCategories = map[string][]string{
	"A1Z26 Cipher Decode":                {catEncryptionEncoding},
	"A1Z26 Cipher Encode":                {catEncryptionEncoding},
	"ADD":                                {catEncryptionEncoding},
	"Add Text To Image":                  {catMultimedia},
	"AES Decrypt":                        {catEncryptionEncoding},
	"AES Encrypt":                        {catEncryptionEncoding},
	"AES Key Unwrap":                     {catEncryptionEncoding},
	"AES Key Wrap":                       {catEncryptionEncoding},
	"AMF Decode":                         {catDataFormat},
	"AMF Encode":                         {catDataFormat},
	"AND":                                {catEncryptionEncoding},
	"Add line numbers":                   {catUtils},
	"Adler-32 Checksum":                  {catHashing},
	"Affine Cipher Decode":               {catEncryptionEncoding},
	"Affine Cipher Encode":               {catEncryptionEncoding},
	"Alternating Caps":                   {catUtils},
	"Analyse hash":                       {catHashing},
	"Ascon Decrypt":                      {catEncryptionEncoding},
	"Ascon Encrypt":                      {catEncryptionEncoding},
	"Ascon Hash":                         {catHashing},
	"Ascon MAC":                          {catHashing},
	"Argon2":                             {catHashing},
	"Argon2 compare":                     {catHashing},
	"Atbash Cipher":                      {catEncryptionEncoding},
	"Avro to JSON":                       {catDataFormat},
	"Bacon Cipher Decode":                {catEncryptionEncoding},
	"Bacon Cipher Encode":                {catEncryptionEncoding},
	"Bcrypt":                             {catEncryptionEncoding, catHashing},
	"Bcrypt compare":                     {catHashing},
	"Bcrypt parse":                       {catHashing},
	"Bifid Cipher Decode":                {catEncryptionEncoding},
	"Bifid Cipher Encode":                {catEncryptionEncoding},
	"Bit shift left":                     {catEncryptionEncoding},
	"Bit shift right":                    {catEncryptionEncoding},
	"Blowfish Decrypt":                   {catEncryptionEncoding},
	"Blur Image":                         {catMultimedia},
	"Blowfish Encrypt":                   {catEncryptionEncoding},
	"BLAKE2b":                            {catHashing},
	"BLAKE2s":                            {catHashing},
	"BLAKE3":                             {catHashing},
	"Bombe":                              {catEncryptionEncoding},
	"BSON deserialise":                   {catCodeTidy},
	"BSON serialise":                     {catCodeTidy},
	"Bzip2 Compress":                     {catCompression},
	"Bzip2 Decompress":                   {catCompression},
	"Caesar Box Cipher":                  {catEncryptionEncoding},
	"Caret/M-decode":                     {catDataFormat},
	"Cartesian Product":                  {catArithmeticLogic},
	"CBOR Decode":                        {catDataFormat},
	"CBOR Encode":                        {catDataFormat},
	"Cetacean Cipher Decode":             {catEncryptionEncoding},
	"Cetacean Cipher Encode":             {catEncryptionEncoding},
	"ChaCha":                             {catEncryptionEncoding},
	"Change IP format":                   {catNetworking},
	"CipherSaber2 Decrypt":               {catEncryptionEncoding},
	"CipherSaber2 Encrypt":               {catEncryptionEncoding},
	"Citrix CTX1 Decode":                 {catEncryptionEncoding},
	"Citrix CTX1 Encode":                 {catEncryptionEncoding},
	"CMAC":                               {catHashing},
	"Colossus":                           {catEncryptionEncoding},
	"Compare CTPH hashes":                {catHashing},
	"Compare SSDEEP hashes":              {catHashing},
	"Convert area":                       {catUtils},
	"Convert co-ordinate format":         {catUtils},
	"Convert data units":                 {catUtils},
	"Convert distance":                   {catUtils},
	"Convert Image Format":               {catMultimedia},
	"Convert Leet Speak":                 {catLanguage},
	"Convert mass":                       {catUtils},
	"Convert speed":                      {catUtils},
	"Convert to NATO alphabet":           {catLanguage},
	"Count occurrences":                  {catUtils},
	"Contain Image":                      {catMultimedia},
	"Cover Image":                        {catMultimedia},
	"Crop Image":                         {catMultimedia},
	"CRC Checksum":                       {catHashing},
	"CSS Beautify":                       {catCodeTidy},
	"CSS Minify":                         {catCodeTidy},
	"CSS selector":                       {catExtractors, catCodeTidy},
	"CTPH":                               {catHashing},
	"CSV to JSON":                        {catDataFormat},
	"DNS over HTTPS":                     {catNetworking},
	"DateTime Delta":                     {catDateTime},
	"Dechunk HTTP response":              {catNetworking},
	"Decode NetBIOS Name":                {catNetworking},
	"Decode text":                        {catDataFormat, catLanguage},
	"Defang IP Addresses":                {catNetworking},
	"Defang URL":                         {catNetworking},
	"Derive EVP key":                     {catEncryptionEncoding},
	"Derive HKDF key":                    {catEncryptionEncoding},
	"Derive PBKDF2 key":                  {catEncryptionEncoding},
	"DES Decrypt":                        {catEncryptionEncoding},
	"DES Encrypt":                        {catEncryptionEncoding},
	"Detect File Type":                   {catForensics},
	"Disassemble ARM":                    {catOther},
	"Disassemble x86":                    {catOther},
	"Generate QR Code":                   {catOther},
	"Diff":                               {catUtils, catCodeTidy},
	"Dither Image":                       {catMultimedia},
	"Divide":                             {catArithmeticLogic},
	"Drop bytes":                         {catUtils},
	"Drop nth bytes":                     {catUtils},
	"ECDSA Sign":                         {catPublicKey},
	"ECDSA Signature Conversion":         {catPublicKey},
	"ECDSA Verify":                       {catPublicKey},
	"ELF Info":                           {catForensics},
	"Encode NetBIOS Name":                {catNetworking},
	"Encode text":                        {catDataFormat, catLanguage},
	"Enigma":                             {catEncryptionEncoding},
	"Escape Smart Characters":            {catDataFormat},
	"Escape Unicode Characters":          {catDataFormat},
	"Escape string":                      {catUtils},
	"Expand alphabet range":              {catUtils},
	"Extract Audio Metadata":             {catExtractors, catForensics},
	"Extract EXIF":                       {catExtractors, catForensics, catMultimedia},
	"Extract Files":                      {catExtractors, catForensics},
	"Extract ID3":                        {catExtractors},
	"Extract IP addresses":               {catExtractors},
	"Extract LSB":                        {catForensics},
	"Extract MAC addresses":              {catExtractors},
	"Extract RGBA":                       {catForensics},
	"Extract URLs":                       {catExtractors},
	"Extract dates":                      {catDateTime, catExtractors},
	"Extract domains":                    {catExtractors},
	"Extract email addresses":            {catExtractors},
	"Extract file paths":                 {catExtractors},
	"Extract hashes":                     {catExtractors},
	"Fang URL":                           {catNetworking},
	"Fernet Decrypt":                     {catEncryptionEncoding},
	"Fernet Encrypt":                     {catEncryptionEncoding},
	"File Tree":                          {catUtils},
	"Filter":                             {catUtils},
	"Find / Replace":                     {catUtils},
	"Flask Session Decode":               {catEncryptionEncoding},
	"Flask Session Sign":                 {catEncryptionEncoding},
	"Flask Session Verify":               {catEncryptionEncoding},
	"Fletcher-16 Checksum":               {catHashing},
	"Fletcher-32 Checksum":               {catHashing},
	"Fletcher-64 Checksum":               {catHashing},
	"Fletcher-8 Checksum":                {catHashing},
	"Flip Image":                         {catMultimedia},
	"Format MAC addresses":               {catNetworking},
	"From Base":                          {catDataFormat},
	"From Base32":                        {catDataFormat},
	"From Base45":                        {catDataFormat},
	"From Base58":                        {catDataFormat},
	"From Base62":                        {catDataFormat},
	"From Base64":                        {catDataFormat},
	"From Base85":                        {catDataFormat},
	"From Base92":                        {catDataFormat},
	"From BCD":                           {catDataFormat},
	"From Bech32":                        {catDataFormat},
	"From Binary":                        {catDataFormat},
	"From Braille":                       {catDataFormat},
	"From Case Insensitive Regex":        {catUtils},
	"From Charcode":                      {catDataFormat},
	"From Decimal":                       {catDataFormat},
	"From Float":                         {catDataFormat},
	"From HTML Entity":                   {catDataFormat},
	"From Hex":                           {catDataFormat},
	"From Hex Content":                   {catDataFormat},
	"From Hexdump":                       {catDataFormat},
	"From MessagePack":                   {catDataFormat, catCodeTidy},
	"From Modhex":                        {catDataFormat},
	"From Morse Code":                    {catEncryptionEncoding},
	"From Octal":                         {catDataFormat},
	"From Punycode":                      {catDataFormat},
	"From Quoted Printable":              {catDataFormat},
	"From UNIX Timestamp":                {catDateTime},
	"Fuzzy Match":                        {catUtils},
	"Generate all checksums":             {catHashing},
	"Generic Code Beautify":              {catCodeTidy},
	"Generate all hashes":                {catHashing},
	"Generate ECDSA Key Pair":            {catPublicKey},
	"Generate Image":                     {catMultimedia},
	"Generate PGP Key Pair":              {catPublicKey},
	"Generate RSA Key Pair":              {catPublicKey},
	"Get All Casings":                    {catUtils},
	"Get Time":                           {catDateTime},
	"GOST Decrypt":                       {catEncryptionEncoding},
	"GOST Encrypt":                       {catEncryptionEncoding},
	"GOST Hash":                          {catHashing},
	"GOST Key Unwrap":                    {catEncryptionEncoding},
	"GOST Key Wrap":                      {catEncryptionEncoding},
	"GOST Sign":                          {catEncryptionEncoding},
	"GOST Verify":                        {catEncryptionEncoding},
	"Group IP addresses":                 {catNetworking},
	"Gunzip":                             {catCompression},
	"Gzip":                               {catCompression},
	"HAS-160":                            {catHashing},
	"HASSH Client Fingerprint":           {catNetworking},
	"HASSH Server Fingerprint":           {catNetworking},
	"HMAC":                               {catHashing},
	"HTTP request":                       {catNetworking},
	"Hamming Distance":                   {catUtils},
	"Head":                               {catUtils},
	"Heatmap chart":                      {catMultimedia},
	"Hex Density chart":                  {catMultimedia},
	"Hex to Object Identifier":           {catPublicKey},
	"Hex to PEM":                         {catDataFormat, catPublicKey},
	"IPv6 Transition Addresses":          {catNetworking},
	"Image Brightness / Contrast":        {catMultimedia},
	"Image Filter":                       {catMultimedia},
	"Image Hue/Saturation/Lightness":     {catMultimedia},
	"Image Opacity":                      {catMultimedia},
	"Invert Image":                       {catMultimedia},
	"JA3 Fingerprint":                    {catNetworking},
	"JA3S Fingerprint":                   {catNetworking},
	"JA4 Fingerprint":                    {catNetworking},
	"JA4Server Fingerprint":              {catNetworking},
	"JPath expression":                   {catExtractors, catCodeTidy},
	"Jsonata Query":                      {catExtractors},
	"JSON Beautify":                      {catCodeTidy},
	"JSON Minify":                        {catCodeTidy},
	"JSON to CSV":                        {catDataFormat},
	"JSON to YAML":                       {catDataFormat},
	"JWK to PEM":                         {catPublicKey},
	"JWT Decode":                         {catEncryptionEncoding},
	"JWT Sign":                           {catEncryptionEncoding},
	"JWT Verify":                         {catEncryptionEncoding},
	"JavaScript Beautify":                {catCodeTidy},
	"JavaScript Minify":                  {catCodeTidy},
	"JavaScript Parser":                  {catCodeTidy},
	"Jq":                                 {catCodeTidy},
	"Keccak":                             {catHashing},
	"LS47 Decrypt":                       {catEncryptionEncoding},
	"LS47 Encrypt":                       {catEncryptionEncoding},
	"LZNT1 Decompress":                   {catCompression},
	"LZ4 Compress":                       {catCompression},
	"LZ4 Decompress":                     {catCompression},
	"LZMA Compress":                      {catCompression},
	"LZMA Decompress":                    {catCompression},
	"LZString Compress":                  {catCompression},
	"LZString Decompress":                {catCompression},
	"Levenshtein Distance":               {catUtils},
	"LM Hash":                            {catHashing},
	"Lorenz":                             {catEncryptionEncoding},
	"Luhn Checksum":                      {catHashing},
	"MD2":                                {catHashing},
	"MD4":                                {catHashing},
	"MD5":                                {catHashing},
	"MD6":                                {catHashing},
	"Mean":                               {catArithmeticLogic},
	"Median":                             {catArithmeticLogic},
	"MIME Decoding":                      {catDataFormat},
	"Microsoft Script Decoder":           {catCodeTidy},
	"Multiple Bombe":                     {catEncryptionEncoding},
	"Multiply":                           {catArithmeticLogic},
	"MurmurHash3":                        {catHashing},
	"Normalise Image":                    {catMultimedia},
	"Normalise Unicode":                  {catDataFormat},
	"NOT":                                {catEncryptionEncoding},
	"NT Hash":                            {catHashing},
	"OR":                                 {catEncryptionEncoding},
	"Object Identifier to Hex":           {catPublicKey},
	"Offset checker":                     {catUtils},
	"Optical Character Recognition":      {catMultimedia},
	"PEM to Hex":                         {catDataFormat, catPublicKey},
	"PEM to JWK":                         {catPublicKey},
	"PGP Decrypt":                        {catPublicKey},
	"PHP Deserialize":                    {catCodeTidy},
	"PHP Serialize":                      {catCodeTidy},
	"PGP Decrypt and Verify":             {catPublicKey},
	"PGP Encrypt":                        {catPublicKey},
	"PGP Encrypt and Sign":               {catPublicKey},
	"PGP Sign":                           {catPublicKey},
	"PGP Verify":                         {catPublicKey},
	"PRESENT Decrypt":                    {catEncryptionEncoding},
	"PRESENT Encrypt":                    {catEncryptionEncoding},
	"Pad lines":                          {catUtils},
	"Parity Bit":                         {catHashing},
	"Parse ASN.1 hex string":             {catDataFormat, catPublicKey},
	"Parse CSR":                          {catPublicKey},
	"Parse DateTime":                     {catDateTime},
	"Parse Ethernet frame":               {catNetworking},
	"Parse IP range":                     {catNetworking},
	"Parse IPv4 header":                  {catNetworking},
	"Parse IPv6 address":                 {catNetworking},
	"Parse ObjectID timestamp":           {catUtils},
	"Parse SSH Host Key":                 {catNetworking, catPublicKey},
	"Parse TCP":                          {catNetworking},
	"Parse TLS record":                   {catNetworking},
	"Parse TLV":                          {catDataFormat},
	"Parse UDP":                          {catNetworking},
	"Parse UNIX file permissions":        {catUtils},
	"Parse URI":                          {catNetworking},
	"Parse User Agent":                   {catNetworking},
	"Parse X.509 CRL":                    {catPublicKey},
	"Parse X.509 certificate":            {catPublicKey},
	"Parse colour code":                  {catUtils},
	"Play Media":                         {catMultimedia},
	"Power Set":                          {catArithmeticLogic},
	"Protobuf Decode":                    {catNetworking},
	"Protobuf Encode":                    {catNetworking},
	"Pseudo-Random Number Generator":     {catOther},
	"Public Key from Certificate":        {catPublicKey},
	"Public Key from Private Key":        {catPublicKey},
	"RC2 Decrypt":                        {catEncryptionEncoding},
	"RC2 Encrypt":                        {catEncryptionEncoding},
	"RC4":                                {catEncryptionEncoding},
	"RC4 Drop":                           {catEncryptionEncoding},
	"RC6 Decrypt":                        {catEncryptionEncoding},
	"RC6 Encrypt":                        {catEncryptionEncoding},
	"ROR13":                              {catEncryptionEncoding},
	"RIPEMD":                             {catHashing},
	"ROT13":                              {catEncryptionEncoding},
	"ROT13 Brute Force":                  {catEncryptionEncoding},
	"ROT47":                              {catEncryptionEncoding},
	"ROT47 Brute Force":                  {catEncryptionEncoding},
	"ROT8000":                            {catEncryptionEncoding},
	"Rabbit":                             {catEncryptionEncoding},
	"Randomize Colour Palette":           {catForensics},
	"RSA Decrypt":                        {catPublicKey},
	"RSA Encrypt":                        {catPublicKey},
	"RSA Sign":                           {catPublicKey},
	"RSA Verify":                         {catPublicKey},
	"Rail Fence Cipher Decode":           {catEncryptionEncoding},
	"Rail Fence Cipher Encode":           {catEncryptionEncoding},
	"RAKE":                               {catExtractors},
	"Raw Deflate":                        {catCompression},
	"Raw Inflate":                        {catCompression},
	"Regular expression":                 {catUtils, catExtractors},
	"Strings":                            {catExtractors},
	"Template":                           {catExtractors},
	"Remove EXIF":                        {catForensics, catMultimedia},
	"Render Image":                       {catMultimedia},
	"Resize Image":                       {catMultimedia},
	"Render Markdown":                    {catCodeTidy},
	"Render PDF":                         {catMultimedia},
	"Remove ANSI Escape Codes":           {catUtils},
	"Remove Diacritics":                  {catLanguage},
	"Remove line numbers":                {catUtils},
	"Remove null bytes":                  {catUtils},
	"Remove whitespace":                  {catUtils},
	"Reverse":                            {catUtils},
	"Rotate Image":                       {catMultimedia},
	"Rison Decode":                       {catDataFormat},
	"Rison Encode":                       {catDataFormat},
	"Rotate left":                        {catEncryptionEncoding},
	"Rotate right":                       {catEncryptionEncoding},
	"Scan for Embedded Files":            {catForensics},
	"SHA0":                               {catHashing},
	"SHA1":                               {catHashing},
	"SHA224":                             {catHashing},
	"SHA256":                             {catHashing},
	"SHA3":                               {catHashing},
	"SHA384":                             {catHashing},
	"SHA512":                             {catHashing},
	"SIGABA":                             {catEncryptionEncoding},
	"SM2 Decrypt":                        {catPublicKey},
	"SM2 Encrypt":                        {catPublicKey},
	"SM3":                                {catHashing},
	"SSDEEP":                             {catHashing},
	"SM4 Decrypt":                        {catEncryptionEncoding},
	"SM4 Encrypt":                        {catEncryptionEncoding},
	"SQL Beautify":                       {catCodeTidy},
	"SQL Minify":                         {catCodeTidy},
	"SUB":                                {catEncryptionEncoding},
	"Salsa20":                            {catEncryptionEncoding},
	"Scatter chart":                      {catMultimedia},
	"Scrypt":                             {catEncryptionEncoding, catHashing},
	"Series chart":                       {catMultimedia},
	"Set Difference":                     {catArithmeticLogic},
	"Set Intersection":                   {catArithmeticLogic},
	"Set Union":                          {catArithmeticLogic},
	"Shake":                              {catHashing},
	"Sharpen Image":                      {catMultimedia},
	"Show Base64 offsets":                {catDataFormat},
	"Show on map":                        {catUtils},
	"Shuffle":                            {catUtils},
	"Sleep":                              {catUtils},
	"Snefru":                             {catHashing},
	"Sort":                               {catUtils},
	"Split":                              {catUtils},
	"Split Colour Channels":              {catMultimedia},
	"Standard Deviation":                 {catArithmeticLogic},
	"Streebog":                           {catHashing},
	"Strip HTML tags":                    {catCodeTidy},
	"Strip HTTP headers":                 {catNetworking},
	"Strip IPv4 header":                  {catNetworking},
	"Strip TCP header":                   {catNetworking},
	"Strip UDP header":                   {catNetworking},
	"Substitute":                         {catEncryptionEncoding},
	"Subtract":                           {catArithmeticLogic},
	"Sum":                                {catArithmeticLogic},
	"Swap case":                          {catUtils},
	"Swap endianness":                    {catDataFormat},
	"Symmetric Difference":               {catArithmeticLogic},
	"Syntax highlighter":                 {catCodeTidy},
	"TCP/IP Checksum":                    {catHashing},
	"TEA Decrypt":                        {catEncryptionEncoding},
	"TEA Encrypt":                        {catEncryptionEncoding},
	"Tail":                               {catUtils},
	"Take bytes":                         {catUtils},
	"Tar":                                {catCompression},
	"Take nth bytes":                     {catUtils},
	"Text Encoding Brute Force":          {catDataFormat},
	"Text-Integer Conversion":            {catDataFormat},
	"To Base":                            {catDataFormat},
	"To Base32":                          {catDataFormat},
	"To Base45":                          {catDataFormat},
	"To Base58":                          {catDataFormat},
	"To Base62":                          {catDataFormat},
	"To Base64":                          {catDataFormat},
	"To Base85":                          {catDataFormat},
	"To Base92":                          {catDataFormat},
	"To BCD":                             {catDataFormat},
	"To Bech32":                          {catDataFormat},
	"To Binary":                          {catDataFormat},
	"To Braille":                         {catDataFormat},
	"To Case Insensitive Regex":          {catUtils},
	"To Charcode":                        {catDataFormat},
	"To Decimal":                         {catDataFormat},
	"To Float":                           {catDataFormat},
	"To HTML Entity":                     {catDataFormat},
	"To Camel case":                      {catCodeTidy},
	"To Hex":                             {catDataFormat},
	"To Hex Content":                     {catDataFormat},
	"To Hexdump":                         {catDataFormat},
	"To Lower case":                      {catUtils},
	"To Kebab case":                      {catCodeTidy},
	"To MessagePack":                     {catDataFormat, catCodeTidy},
	"To Modhex":                          {catDataFormat},
	"To Morse Code":                      {catEncryptionEncoding},
	"To Octal":                           {catDataFormat},
	"To Punycode":                        {catDataFormat},
	"To Quoted Printable":                {catDataFormat},
	"To Snake case":                      {catCodeTidy},
	"To Table":                           {catUtils},
	"To UNIX Timestamp":                  {catDateTime},
	"To Upper case":                      {catUtils},
	"Translate DateTime Format":          {catDateTime},
	"Triple DES Decrypt":                 {catEncryptionEncoding},
	"Triple DES Encrypt":                 {catEncryptionEncoding},
	"Twofish Decrypt":                    {catEncryptionEncoding},
	"Twofish Encrypt":                    {catEncryptionEncoding},
	"Typex":                              {catEncryptionEncoding},
	"Parse QR Code":                      {catOther},
	"Chi Square":                         {catOther},
	"Entropy":                            {catOther},
	"Frequency distribution":             {catOther},
	"Index of Coincidence":               {catOther},
	"Analyse UUID":                       {catOther},
	"Automated Validation Test Op":       {catOther},
	"Generate De Bruijn Sequence":        {catOther},
	"Haversine distance":                 {catOther},
	"HTML To Text":                       {catOther},
	"Unzip":                              {catCompression},
	"Untar":                              {catCompression},
	"View Bit Plane":                     {catForensics},
	"YARA Rules":                         {catForensics},
	"XKCD Random Number":                 {catOther},
	"Generate Lorem Ipsum":               {catOther},
	"Numberwang":                         {catOther},
	"P-list Viewer":                      {catOther},
	"Pseudo-Random Integer Generator":    {catOther},
	"Generate HOTP":                      {catOther},
	"Generate TOTP":                      {catOther},
	"Generate UUID":                      {catOther},
	"UNIX Timestamp to Windows Filetime": {catDateTime},
	"URL Decode":                         {catDataFormat, catNetworking},
	"Unescape Unicode Characters":        {catDataFormat, catLanguage},
	"Unicode Text Format":                {catLanguage},
	"URL Encode":                         {catDataFormat, catNetworking},
	"Unescape string":                    {catUtils},
	"Unique":                             {catUtils},
	"VarInt Decode":                      {catNetworking},
	"VarInt Encode":                      {catNetworking},
	"Vigenère Decode":                    {catEncryptionEncoding},
	"Vigenère Encode":                    {catEncryptionEncoding},
	"Whirlpool":                          {catHashing},
	"Windows Filetime to UNIX Timestamp": {catDateTime},
	"Wrap":                               {catUtils},
	"XOR":                                {catEncryptionEncoding},
	"XOR Brute Force":                    {catEncryptionEncoding},
	"XOR Checksum":                       {catHashing},
	"XML Beautify":                       {catCodeTidy},
	"XML Minify":                         {catCodeTidy},
	"XPath expression":                   {catExtractors, catCodeTidy},
	"XSalsa20":                           {catEncryptionEncoding},
	"XTEA Decrypt":                       {catEncryptionEncoding},
	"XTEA Encrypt":                       {catEncryptionEncoding},
	"XXTEA Decrypt":                      {catEncryptionEncoding},
	"XXTEA Encrypt":                      {catEncryptionEncoding},
	"YAML to JSON":                       {catDataFormat},
	"Zip":                                {catCompression},
	"Zlib Deflate":                       {catCompression},
	"Zlib Inflate":                       {catCompression},
}

// categoriesOf returns the categories an operation belongs to (sorted), or a
// single "Uncategorized" bucket if the name is absent (which the reconciliation
// test prevents for registered operations).
func categoriesOf(name string) []string {
	cats, ok := opCategories[name]
	if !ok || len(cats) == 0 {
		return []string{"Uncategorized"}
	}
	out := slices.Clone(cats)
	sort.Strings(out)
	return out
}
