package cmd

// opSummaries holds curated one-line summaries (cobra Short text) for
// operations, keyed by display name. Entries override the summary derived from
// the CyberChef description by deriveSummary — they exist for operations whose
// first description sentence is too long and would otherwise be truncated. Keep
// each under maxSummaryLen so help and `cchef list` do not wrap; the full
// description remains the Long help.
var opSummaries = map[string]string{
	"A1Z26 Cipher Decode":            "Converts number sequences back to letters",
	"A1Z26 Cipher Encode":            "Converts letters to their alphabet position",
	"AES Decrypt":                    "Decrypts AES (CBC, CFB, OFB, CTR, GCM, ECB)",
	"AES Encrypt":                    "Encrypts with AES (CBC, CFB, OFB, CTR, GCM, ECB)",
	"AES Key Unwrap":                 "Unwraps key material with RFC3394 AES-KW",
	"AES Key Wrap":                   "Wraps key material with RFC3394 AES-KW",
	"AMF Decode":                     "Deserializes AMF binary data into JSON",
	"AMF Encode":                     "Serializes JSON into AMF binary data",
	"Add line numbers":               "Prepends a line number to each line",
	"Analyse hash":                   "Guesses the hash algorithm from the digest length",
	"Adler-32 Checksum":              "Computes the Adler-32 checksum as hex",
	"Affine Cipher Decode":           "Decrypts an Affine cipher: (y - b) * a⁻¹ mod 26",
	"Affine Cipher Encode":           "Encrypts with an Affine cipher: (ax + b) mod 26",
	"Alternating Caps":               "Applies aLtErNaTiNg capitalisation",
	"Ascon Decrypt":                  "Ascon-AEAD128 authenticated decryption (SP 800-232)",
	"Ascon Encrypt":                  "Ascon-AEAD128 authenticated encryption (SP 800-232)",
	"Atbash Cipher":                  "Mirror-substitution cipher (a<->z, b<->y)",
	"Bacon Cipher Decode":            "Decodes a Baconian steganographic cipher",
	"Bacon Cipher Encode":            "Encodes text as a Baconian cipher",
	"Bcrypt":                         "Hashes a password with bcrypt",
	"Bcrypt parse":                   "Extracts the rounds, salt and hash from a bcrypt hash",
	"Bifid Cipher Decode":            "Decodes a Bifid cipher with a keyword",
	"Bifid Cipher Encode":            "Encodes text with a keyed Bifid cipher",
	"Bit shift left":                 "Shifts each byte's bits left by an amount",
	"Bit shift right":                "Shifts each byte's bits right by an amount",
	"Blowfish Decrypt":               "Decrypts with the Blowfish block cipher",
	"Blowfish Encrypt":               "Encrypts with the Blowfish block cipher",
	"Bombe":                          "Attacks Enigma with the Bombe (needs a crib)",
	"Caesar Box Cipher":              "Transposition cipher: write in rows, read by column",
	"Caret/M-decode":                 "Decodes caret/M-notation escapes (cat -v)",
	"Cartesian Product":              "Cartesian product of multiple sets",
	"CBOR Decode":                    "Decodes CBOR (RFC 8949) binary data into JSON",
	"CBOR Encode":                    "Encodes JSON into canonical CBOR (RFC 8949)",
	"ChaCha":                         "ChaCha stream cipher (8/12/20 rounds)",
	"CipherSaber2 Decrypt":           "Decrypts CipherSaber-2 (RC4-based) ciphertext",
	"CipherSaber2 Encrypt":           "Encrypts with CipherSaber-2 (RC4-based)",
	"Citrix CTX1 Decode":             "Decodes a Citrix CTX1 password hash to plaintext",
	"Colossus":                       "Emulates the WW2 Colossus codebreaking computer",
	"Count occurrences":              "Counts occurrences of a string in the input",
	"DateTime Delta":                 "Adds or subtracts a delta to a DateTime",
	"Dechunk HTTP response":          "Decodes a chunked HTTP response body",
	"Decode NetBIOS Name":            "Decodes an encoded NetBIOS name",
	"Defang IP Addresses":            "Defangs IPs to make them safe to share",
	"Defang URL":                     "Defangs a URL to make it safe to share",
	"Derive EVP key":                 "OpenSSL EVP_BytesToKey password-based KDF",
	"CRC Checksum":                   "Cyclic Redundancy Check, 170+ named CRC variants",
	"Derive HKDF key":                "HMAC-based key derivation (HKDF, RFC 5869)",
	"Derive PBKDF2 key":              "Password-based key derivation (PBKDF2, RFC 2898)",
	"DES Decrypt":                    "Decrypts with the DES block cipher",
	"DES Encrypt":                    "Encrypts with the DES block cipher",
	"Triple DES Decrypt":             "Decrypts with the Triple DES (3DES) cipher",
	"Triple DES Encrypt":             "Encrypts with the Triple DES (3DES) cipher",
	"Diff":                           "Highlights differences between two inputs",
	"Drop nth bytes":                 "Drops every nth byte from a given offset",
	"Encode NetBIOS Name":            "Encodes a name with NetBIOS name encoding",
	"Escape Smart Characters":        "Converts typographic Unicode chars to ASCII",
	"Escape string":                  "Escapes special characters in a string",
	"Expand alphabet range":          "Expands an alphabet range to its characters",
	"Extract dates":                  "Extracts dates in common formats",
	"Fang URL":                       "Re-fangs a defanged URL",
	"Fernet Decrypt":                 "Decrypts a Fernet token (AES-128-CBC + HMAC)",
	"Fernet Encrypt":                 "Encrypts into a Fernet token (AES-128 + HMAC)",
	"Filter":                         "Keeps input sections matching a regex",
	"Flask Session Decode":           "Decodes a Flask session cookie into JSON",
	"Flask Session Sign":             "Signs a JSON payload into a Flask session cookie",
	"Flask Session Verify":           "Verifies a Flask session cookie's HMAC signature",
	"Fletcher-16 Checksum":           "Fletcher-16 position-dependent checksum",
	"Fletcher-32 Checksum":           "Fletcher-32 position-dependent checksum",
	"Fletcher-64 Checksum":           "Fletcher-64 position-dependent checksum",
	"Fletcher-8 Checksum":            "Fletcher-8 position-dependent checksum",
	"From Base":                      "Converts a number from base 2-36 to decimal",
	"From Base45":                    "Decodes a Base45 string (RFC 9285)",
	"From Base64":                    "Decodes a Base64 string to raw bytes",
	"From Base85":                    "Decodes a Base85 (Ascii85) string",
	"From BCD":                       "Decodes Binary-Coded Decimal to a number",
	"From Bech32":                    "Decodes a Bech32/Bech32m string",
	"From Case Insensitive Regex":    "Converts a case-insensitive regex to sensitive",
	"From Decimal":                   "Converts an ordinal integer array to bytes",
	"From HTML Entity":               "Converts HTML entities back into characters",
	"From Morse Code":                "Translates Morse Code back into text",
	"From Punycode":                  "Decodes Punycode ASCII back to Unicode (RFC 3492)",
	"Fuzzy Match":                    "Fuzzy-searches for a pattern in the input",
	"Get All Casings":                "Outputs every upper/lower-case combination",
	"Get Time":                       "Time elapsed since the UNIX epoch",
	"GOST Decrypt":                   "Decrypts with a GOST cipher (Magma/Kuznyechik)",
	"GOST Encrypt":                   "Encrypts with a GOST cipher (Magma/Kuznyechik)",
	"GOST Hash":                      "GOST R 34.11 hash (94 or 2012 Streebog)",
	"GOST Key Unwrap":                "Unwraps a key wrapped with a GOST cipher",
	"GOST Key Wrap":                  "Wraps key material with a GOST cipher",
	"GOST Sign":                      "Signs a message with a GOST cipher MAC",
	"GOST Verify":                    "Verifies a GOST cipher MAC signature",
	"HAS-160":                        "Korean 160-bit hash (KCDSA), SHA-1-like",
	"HMAC":                           "Computes an HMAC over the input with a key",
	"Hamming Distance":               "Hamming distance between two samples",
	"Hex to Object Identifier":       "Decodes ASN.1 hex content octets to an OID",
	"Hex to PEM":                     "Wraps a hex DER string in PEM armor",
	"JSON to CSV":                    "Converts JSON to CSV (RFC 4180)",
	"JWT Decode":                     "Decodes a JWT's payload without verifying it",
	"JWT Sign":                       "Signs a JSON object as a JSON Web Token",
	"JWT Verify":                     "Verifies a JWT's signature and returns its payload",
	"LS47 Decrypt":                   "Decrypts with the LS47 (ElsieFour 7x7) cipher",
	"LS47 Encrypt":                   "Encrypts with the LS47 (ElsieFour 7x7) cipher",
	"Levenshtein Distance":           "Levenshtein (edit) distance of two samples",
	"Lorenz":                         "Emulates the Lorenz SZ40/42 cipher machine",
	"MIME Decoding":                  "Decodes RFC 2047 MIME encoded-word headers",
	"Normalise Unicode":              "Normalises text (NFC/NFD/NFKC/NFKD)",
	"Object Identifier to Hex":       "Encodes an OID to ASN.1 hex content octets",
	"Offset checker":                 "Highlights byte offsets shared by samples",
	"PEM to Hex":                     "Extracts hex DER from PEM blocks",
	"PRESENT Decrypt":                "Decrypts with the PRESENT lightweight cipher",
	"PRESENT Encrypt":                "Encrypts with the PRESENT lightweight cipher",
	"Pad lines":                      "Pads the start or end of each line",
	"Parity Bit":                     "Adds or removes a parity bit on binary data",
	"Parse ASN.1 hex string":         "Parses ASN.1 hex into a readable structure tree",
	"Parse CSR":                      "Describes an X.509 Certificate Signing Request",
	"Parse DateTime":                 "Parses a DateTime and shows its components",
	"Parse Ethernet frame":           "Parses an Ethernet frame into fields",
	"Parse IPv4 header":              "Parses an IPv4 header into its fields",
	"Parse IPv6 address":             "Shows long and short forms of an IPv6 address",
	"Parse ObjectID timestamp":       "Extracts the timestamp from a MongoDB ObjectID",
	"Parse TLV":                      "Parses Type-Length-Value data into JSON",
	"Parse URI":                      "Pretty-prints the parts of a URI",
	"Parse X.509 CRL":                "Describes an X.509 Certificate Revocation List",
	"Parse X.509 certificate":        "Describes an X.509 certificate, openssl-style",
	"Parse User Agent":               "Identifies details in a user-agent string",
	"Parse colour code":              "Converts a colour code between formats",
	"Pseudo-Random Number Generator": "Generates cryptographically-secure random data",
	"RC2 Decrypt":                    "Decrypts with the RC2 (ARC2) block cipher",
	"RC2 Encrypt":                    "Encrypts with the RC2 (ARC2) block cipher",
	"RC4":                            "RC4 (ARC4) stream cipher",
	"RC4 Drop":                       "RC4 discarding the initial keystream bytes",
	"RC6 Decrypt":                    "Decrypts with the RC6 block cipher (AES finalist)",
	"RC6 Encrypt":                    "Encrypts with the RC6 block cipher (AES finalist)",
	"ROT13":                          "Caesar cipher rotating letters by an amount",
	"ROT13 Brute Force":              "Tries every ROT13 rotation, filtered by a crib",
	"ROT47":                          "ROT variant over printable ASCII (33-126)",
	"ROT47 Brute Force":              "Tries every ROT47 rotation, filtered by a crib",
	"ROT8000":                        "Caesar cipher over the full Unicode range",
	"Rabbit":                         "Rabbit stream cipher (RFC 4503)",
	"Rail Fence Cipher Decode":       "Decodes text with the Rail Fence cipher",
	"Rail Fence Cipher Encode":       "Encodes text with the Rail Fence cipher",
	"Regular expression":             "Searches the input with your own RE2 regex",
	"Remove line numbers":            "Removes leading line numbers from each line",
	"Remove whitespace":              "Removes selected whitespace characters",
	"Rison Decode":                   "Decodes Rison (compact URI-friendly format) to JSON",
	"Rison Encode":                   "Encodes JSON to Rison, a compact URI-friendly format",
	"Rotate left":                    "Rotates each byte's bits left",
	"Rotate right":                   "Rotates each byte's bits right",
	"MD2":                            "MD2 message digest (RFC 1319, 128-bit)",
	"MD4":                            "MD4 message digest (RFC 1320, 128-bit)",
	"MurmurHash3":                    "MurmurHash v3 (32-bit) with an optional seed",
	"RIPEMD":                         "RIPEMD hash (128/160/256/320-bit)",
	"SHA0":                           "The withdrawn 1993 SHA-0 (160-bit)",
	"SHA3":                           "Computes the SHA-3 (Keccak) digest",
	"SM3":                            "SM3 cryptographic hash (Chinese standard GM/T 0004)",
	"SM4 Decrypt":                    "Decrypt with the SM4 block cipher (GB/T 32907-2016)",
	"SM4 Encrypt":                    "Encrypt with the SM4 block cipher (GB/T 32907-2016)",
	"Salsa20":                        "Salsa20 stream cipher (8-byte nonce)",
	"Scrypt":                         "scrypt password-based key derivation (RFC 7914)",
	"Set Difference":                 "Relative complement of two sets",
	"Shake":                          "SHAKE XOF of SHA-3 with variable output length",
	"Show Base64 offsets":            "Shows a string's three Base64 offset encodings",
	"Shuffle":                        "Randomly reorders input sections",
	"Snefru":                         "Snefru hash (128/256-bit, Merkle 1990)",
	"Sleep":                          "Pauses, then passes the input through",
	"Sort":                           "Sorts input sections by the chosen order",
	"Whirlpool":                      "Whirlpool 512-bit hash (with -0/-T variants)",
	"Split":                          "Splits on one delimiter, rejoins with another",
	"Strip HTTP headers":             "Removes HTTP headers, keeping the body",
	"Strip IPv4 header":              "Strips the IPv4 header, outputting the payload",
	"Strip TCP header":               "Strips the TCP header, outputting the payload",
	"Strip UDP header":               "Strips the UDP header, outputting the payload",
	"Substitute":                     "Substitution cipher mapping bytes to other bytes",
	"TCP/IP Checksum":                "16-bit one's-complement Internet checksum",
	"TEA Decrypt":                    "Decrypt with the TEA block cipher (64-bit blocks)",
	"TEA Encrypt":                    "Encrypt with the TEA block cipher (64-bit blocks)",
	"XTEA Decrypt":                   "Decrypt with the XTEA block cipher",
	"XTEA Encrypt":                   "Encrypt with the XTEA block cipher",
	"XXTEA Decrypt":                  "Decrypt with XXTEA (Corrected Block TEA)",
	"XXTEA Encrypt":                  "Encrypt with XXTEA (Corrected Block TEA)",
	"Twofish Decrypt":                "Decrypt with the Twofish block cipher (AES finalist)",
	"Twofish Encrypt":                "Encrypt with the Twofish block cipher (AES finalist)",
	"Typex":                          "Encipher/decipher with the WW2 Typex machine",
	"ECDSA Verify":                   "Verify an ECDSA signature with an EC public key",
	"PGP Encrypt":                    "Encrypt a message with a recipient's PGP public key",
	"PGP Decrypt":                    "Decrypt a PGP message with a private key",
	"PGP Sign":                       "Sign a message with a PGP private key",
	"PGP Verify":                     "Verify a signed PGP message with a public key",
	"PGP Encrypt and Sign":           "Encrypt and sign a message with PGP",
	"PGP Decrypt and Verify":         "Decrypt and verify a signed PGP message",
	"Generate PGP Key Pair":          "Generate a PGP key pair (RSA or ECC)",
	"RSA Encrypt":                    "Encrypt a message with a PEM RSA public key",
	"RSA Decrypt":                    "Decrypt an RSA message with a PEM private key",
	"RSA Sign":                       "Sign a message with a PEM RSA private key",
	"RSA Verify":                     "Verify a signature with a PEM RSA public key",
	"Generate RSA Key Pair":          "Generate an RSA key pair (PEM, JSON or DER)",
	"Vigenère Decode":                "Decrypt with the Vigenère polyalphabetic cipher",
	"Vigenère Encode":                "Encrypt with the Vigenère polyalphabetic cipher",
	"Swap endianness":                "Reverses byte order within each word",
	"XOR Checksum":                   "Block-wise XOR checksum of the input",
	"XSalsa20":                       "XSalsa20 stream cipher (24-byte nonce)",
	"Take bytes":                     "Keeps a range of bytes from the input",
	"Take nth bytes":                 "Keeps every nth byte from a given offset",
	"Text Encoding Brute Force":      "Tries every character encoding on the input",
	"Text-Integer Conversion":        "Converts text to/from a big integer (dec/hex)",
	"To Base":                        "Converts a decimal number to base 2-36",
	"To Base32":                      "Base32-encodes bytes (A-Z, 2-7)",
	"To Base45":                      "Base45-encodes bytes, used in QR codes",
	"To Base58":                      "Base58-encodes bytes (ambiguity-free alphabet)",
	"To Base62":                      "Base62-encodes bytes as alphanumerics",
	"To Base85":                      "Base85 (Ascii85)-encodes bytes",
	"To Base92":                      "Base92-encodes bytes for compactness",
	"To BCD":                         "Encodes a number as Binary-Coded Decimal",
	"To Bech32":                      "Encodes bytes as a Bech32/Bech32m string",
	"To Binary":                      "Displays each byte as zero-padded binary",
	"To Case Insensitive Regex":      "Converts a regex to case-insensitive form",
	"To Charcode":                    "Converts text to character codes in a base",
	"To Decimal":                     "Converts input to an ordinal integer array",
	"To Hex":                         "Converts input to hex with a delimiter",
	"To Hexdump":                     "Renders input as a classic hexdump",
	"To Modhex":                      "Converts input to modhex with a delimiter",
	"To Morse Code":                  "Translates text into International Morse Code",
	"To Octal":                       "Converts input to octal with a delimiter",
	"To Punycode":                    "Encodes Unicode to Punycode ASCII (RFC 3492)",
	"To Quoted Printable":            "Encodes bytes as Quoted-Printable (RFC 2045)",
	"To UNIX Timestamp":              "Converts a UTC datetime to a UNIX timestamp",
	"To Upper case":                  "Converts the input to upper case",
	"Translate DateTime Format":      "Rewrites a datetime from one format to another",
	"URL Decode":                     "Decodes percent-encoded URL characters",
	"URL Encode":                     "Percent-encodes problematic URL characters",
	"Unescape Unicode Characters":    "Converts unicode escapes back to characters",
	"Unique":                         "Removes duplicate input sections",
	"Wrap":                           "Wraps text to a given line width",
}
