package cmd

// opSummaries holds curated one-line summaries (cobra Short text) for
// operations, keyed by display name. Entries override the summary derived from
// the CyberChef description by deriveSummary — they exist for operations whose
// first description sentence is too long and would otherwise be truncated. Keep
// each under maxSummaryLen so help and `cchef list` do not wrap; the full
// description remains the Long help.
var opSummaries = map[string]string{
	"AMF Decode":                     "Deserializes AMF binary data into JSON",
	"AMF Encode":                     "Serializes JSON into AMF binary data",
	"Add line numbers":               "Prepends a line number to each line",
	"Adler-32 Checksum":              "Computes the Adler-32 checksum as hex",
	"Alternating Caps":               "Applies aLtErNaTiNg capitalisation",
	"Bit shift left":                 "Shifts each byte's bits left by an amount",
	"Bit shift right":                "Shifts each byte's bits right by an amount",
	"Caret/M-decode":                 "Decodes caret/M-notation escapes (cat -v)",
	"Cartesian Product":              "Cartesian product of multiple sets",
	"Count occurrences":              "Counts occurrences of a string in the input",
	"DateTime Delta":                 "Adds or subtracts a delta to a DateTime",
	"Dechunk HTTP response":          "Decodes a chunked HTTP response body",
	"Decode NetBIOS Name":            "Decodes an encoded NetBIOS name",
	"Defang IP Addresses":            "Defangs IPs to make them safe to share",
	"Defang URL":                     "Defangs a URL to make it safe to share",
	"Diff":                           "Highlights differences between two inputs",
	"Drop nth bytes":                 "Drops every nth byte from a given offset",
	"Encode NetBIOS Name":            "Encodes a name with NetBIOS name encoding",
	"Escape string":                  "Escapes special characters in a string",
	"Expand alphabet range":          "Expands an alphabet range to its characters",
	"Extract dates":                  "Extracts dates in common formats",
	"Fang URL":                       "Re-fangs a defanged URL",
	"Filter":                         "Keeps input sections matching a regex",
	"From Base":                      "Converts a number from base 2-36 to decimal",
	"From Base45":                    "Decodes a Base45 string (RFC 9285)",
	"From Base64":                    "Decodes a Base64 string to raw bytes",
	"From Base85":                    "Decodes a Base85 (Ascii85) string",
	"From BCD":                       "Decodes Binary-Coded Decimal to a number",
	"From Case Insensitive Regex":    "Converts a case-insensitive regex to sensitive",
	"From Decimal":                   "Converts an ordinal integer array to bytes",
	"From HTML Entity":               "Converts HTML entities back into characters",
	"Fuzzy Match":                    "Fuzzy-searches for a pattern in the input",
	"Get All Casings":                "Outputs every upper/lower-case combination",
	"Get Time":                       "Time elapsed since the UNIX epoch",
	"HMAC":                           "Computes an HMAC over the input with a key",
	"Hamming Distance":               "Hamming distance between two samples",
	"Hex to PEM":                     "Wraps a hex DER string in PEM armor",
	"Levenshtein Distance":           "Levenshtein (edit) distance of two samples",
	"Offset checker":                 "Highlights byte offsets shared by samples",
	"PEM to Hex":                     "Extracts hex DER from PEM blocks",
	"Pad lines":                      "Pads the start or end of each line",
	"Parse DateTime":                 "Parses a DateTime and shows its components",
	"Parse Ethernet frame":           "Parses an Ethernet frame into fields",
	"Parse IPv4 header":              "Parses an IPv4 header into its fields",
	"Parse IPv6 address":             "Shows long and short forms of an IPv6 address",
	"Parse ObjectID timestamp":       "Extracts the timestamp from a MongoDB ObjectID",
	"Parse URI":                      "Pretty-prints the parts of a URI",
	"Parse User Agent":               "Identifies details in a user-agent string",
	"Parse colour code":              "Converts a colour code between formats",
	"Pseudo-Random Number Generator": "Generates cryptographically-secure random data",
	"ROT13":                          "Caesar cipher rotating letters by an amount",
	"ROT47":                          "ROT variant over printable ASCII (33-126)",
	"ROT8000":                        "Caesar cipher over the full Unicode range",
	"Regular expression":             "Searches the input with your own RE2 regex",
	"Remove line numbers":            "Removes leading line numbers from each line",
	"Remove whitespace":              "Removes selected whitespace characters",
	"Rotate left":                    "Rotates each byte's bits left",
	"Rotate right":                   "Rotates each byte's bits right",
	"SHA3":                           "Computes the SHA-3 (Keccak) digest",
	"Set Difference":                 "Relative complement of two sets",
	"Show Base64 offsets":            "Shows a string's three Base64 offset encodings",
	"Shuffle":                        "Randomly reorders input sections",
	"Sleep":                          "Pauses, then passes the input through",
	"Sort":                           "Sorts input sections by the chosen order",
	"Split":                          "Splits on one delimiter, rejoins with another",
	"Strip HTTP headers":             "Removes HTTP headers, keeping the body",
	"Strip IPv4 header":              "Strips the IPv4 header, outputting the payload",
	"Strip TCP header":               "Strips the TCP header, outputting the payload",
	"Strip UDP header":               "Strips the UDP header, outputting the payload",
	"Swap endianness":                "Reverses byte order within each word",
	"Take bytes":                     "Keeps a range of bytes from the input",
	"Take nth bytes":                 "Keeps every nth byte from a given offset",
	"Text-Integer Conversion":        "Converts text to/from a big integer (dec/hex)",
	"To Base":                        "Converts a decimal number to base 2-36",
	"To Base32":                      "Base32-encodes bytes (A-Z, 2-7)",
	"To Base45":                      "Base45-encodes bytes, used in QR codes",
	"To Base58":                      "Base58-encodes bytes (ambiguity-free alphabet)",
	"To Base62":                      "Base62-encodes bytes as alphanumerics",
	"To Base85":                      "Base85 (Ascii85)-encodes bytes",
	"To Base92":                      "Base92-encodes bytes for compactness",
	"To BCD":                         "Encodes a number as Binary-Coded Decimal",
	"To Binary":                      "Displays each byte as zero-padded binary",
	"To Case Insensitive Regex":      "Converts a regex to case-insensitive form",
	"To Charcode":                    "Converts text to character codes in a base",
	"To Decimal":                     "Converts input to an ordinal integer array",
	"To Hex":                         "Converts input to hex with a delimiter",
	"To Hexdump":                     "Renders input as a classic hexdump",
	"To Modhex":                      "Converts input to modhex with a delimiter",
	"To Octal":                       "Converts input to octal with a delimiter",
	"To Quoted Printable":            "Encodes bytes as Quoted-Printable (RFC 2045)",
	"To UNIX Timestamp":              "Converts a UTC datetime to a UNIX timestamp",
	"To Upper case":                  "Converts the input to upper case",
	"Translate DateTime Format":      "Rewrites a datetime from one format to another",
	"URL Decode":                     "Decodes percent-encoded URL characters",
	"URL Encode":                     "Percent-encodes problematic URL characters",
	"Unescape Unicode Characters":    "Converts unicode escapes back to characters",
	"Unique":                         "Removes duplicate input sections",
	"Wrap":                           "Wraps text to a given line width",
}
