// Code generator for cchef's codepage engine.
//
// Extracts the 140 table-backed decode tables from the `codepage` (cptable)
// npm library that CyberChef bundles, and the 152-charset manifest from
// CyberChef's lib/ChrEnc.mjs, emitting:
//   - internal/ops/codepage_data.bin.gz  (gzipped decode tables)
//   - internal/ops/codepage_charsets.go  (the 152-charset manifest)
//
// Run against the sibling CyberChef checkout:
//   NODE_PATH=../CyberChef/node_modules \
//     node tools/cpgen/gen.js ../CyberChef ./internal/ops
//
// Only decode tables are stored; encode tables derive from them at load time
// (verified identical to cptable's own enc for all 140 codepages).
const fs = require("fs");
const zlib = require("zlib");
const path = require("path");
const cptable = require("codepage");

const cyberchef = process.argv[2];
const outDir = process.argv[3];

// Parse CHR_ENC_CODE_PAGES (name -> codepage) from ChrEnc.mjs, in order.
const chrEnc = fs.readFileSync(path.join(cyberchef, "src/core/lib/ChrEnc.mjs"), "utf8");
const body = chrEnc.match(/CHR_ENC_CODE_PAGES\s*=\s*\{([\s\S]*?)\n\}/)[1];
const pairs = [...body.matchAll(/"([^"]+)"\s*:\s*(\d+)/g)].map(m => [m[1], +m[2]]);
if (pairs.length !== 152) throw new Error("expected 152 charsets, got " + pairs.length);

const magic = {
  1200: "utf16le", 1201: "utf16be", 12000: "utf32le", 12001: "utf32be",
  20127: "ascii", 65000: "utf7", 65001: "utf8",
};

// --- binary decode tables for the table-backed codepages ---
const chunks = [];
const u16 = (v) => { const b = Buffer.allocUnsafe(2); b.writeUInt16BE(v & 0xffff, 0); return b; };
const u32 = (v) => { const b = Buffer.allocUnsafe(4); b.writeUInt32BE(v >>> 0, 0); return b; };

const tableCps = [];
for (const [, cp] of pairs) {
  if (magic[cp] || tableCps.includes(cp)) continue;
  if (!cptable[cp]) continue; // unsupported (ISO-2022) -> handled as absent
  tableCps.push(cp);
}

const header = [u16(tableCps.length)];
const bodyChunks = [];
for (const cp of tableCps) {
  const D = cptable[cp].dec;
  const entries = [];
  for (let d = 0; d < D.length; d++) {
    const c = D[d];
    if (!c) continue; // undefined -> decode error (not stored)
    entries.push([d, c.charCodeAt(0)]);
  }
  bodyChunks.push(u16(cp), u32(entries.length));
  for (const [code, ch] of entries) bodyChunks.push(u16(code), u16(ch));
}
const raw = Buffer.concat([...header, ...bodyChunks]);
const gz = zlib.gzipSync(raw, { level: 9 });
fs.writeFileSync(path.join(outDir, "codepage_data.bin.gz"), gz);

// --- Go manifest of all 152 charsets in order ---
// cptable dispatches a handful of codepages through cached algorithms that
// differ from its general table path, so the manifest records each charset's
// exact dispatch kind.
const sbcsCache = new Set([874, 1250, 1251, 1252, 1253, 1254, 1255, 1256, 10000]);
const dbcsCache = new Set([932, 936, 949, 950]);
function kindOf(cp) {
  if (magic[cp]) return magic[cp];          // utf8/utf7/utf16le/utf16be/utf32le/utf32be/ascii
  if (sbcsCache.has(cp)) return "sbcs";     // cached: 1-byte decode
  if (dbcsCache.has(cp)) return "dbcs";     // cached: 1-byte then 2-byte, no error
  if (cptable[cp]) return "table";          // general: 2-byte-first decode
  return "none";                            // unsupported (ISO-2022) -> error
}
let go = `package ops

// Code generated by tools/cpgen/gen.js from CyberChef's lib/ChrEnc.mjs and the
// bundled 'codepage' (cptable) library. DO NOT EDIT.

// cpCharset is one CyberChef charset: its display name, codepage number, and the
// dispatch "kind" cptable uses for it: a magic encoding ("utf8", "utf7",
// "utf16le", "utf16be", "utf32le", "utf32be", "ascii"), a cached table path
// ("sbcs" 1-byte decode, "dbcs" 1-byte-then-2-byte), the general table path
// ("table", 2-byte-first), or "none" (cptable does not support it — the
// ISO-2022 family, which errors exactly as upstream does).
type cpCharset struct {
	name string
	cp   int
	kind string
}

// cpCharsets lists every CyberChef charset in CHR_ENC_CODE_PAGES order.
var cpCharsets = []cpCharset{
`;
for (const [name, cp] of pairs) {
  go += `\t{${JSON.stringify(name)}, ${cp}, ${JSON.stringify(kindOf(cp))}},\n`;
}
go += "}\n";
fs.writeFileSync(path.join(outDir, "codepage_charsets.go"), go);

console.log(`wrote codepage_data.bin.gz (${gz.length} bytes, ${raw.length} raw), ${tableCps.length} table codepages`);
console.log(`wrote codepage_charsets.go (${pairs.length} charsets)`);
