package ops

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"testing"
)

// codepageVectors is the oracle data generated by tools/cpgen/gen_vectors.js
// from cptable (the library CyberChef wraps).
type codepageVectors struct {
	EncInputs []string `json:"encInputs"`
	DecInputs []string `json:"decInputs"`
	RtStrings []string `json:"rtStrings"`
	Cps       []struct {
		Cp    int       `json:"cp"`
		Name  string    `json:"name"`
		Magic string    `json:"magic"`
		Enc   []*string `json:"enc"`
		Dec   []*string `json:"dec"`
		Rt    []struct {
			S    string  `json:"s"`
			H    *string `json:"h"`
			Back *string `json:"back"`
		} `json:"rt"`
	} `json:"cps"`
}

func loadCodepageVectors(t *testing.T) codepageVectors {
	t.Helper()
	b, err := os.ReadFile("testdata/codepage_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v codepageVectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	return v
}

// TestCodepageEngineDifferential verifies cptableEncode/cptableDecode reproduce
// cptable byte-for-byte across all 152 CyberChef charsets.
func TestCodepageEngineDifferential(t *testing.T) {
	v := loadCodepageVectors(t)
	for _, c := range v.Cps {
		t.Run(c.Name, func(t *testing.T) {
			for i, in := range v.EncInputs {
				got, err := cptableEncode(c.Cp, in)
				want := c.Enc[i]
				if want == nil {
					if err == nil {
						t.Errorf("encode(%q): expected error, got %x", in, got)
					}
					continue
				}
				if err != nil {
					t.Errorf("encode(%q): unexpected error %v (want %s)", in, err, *want)
					continue
				}
				if hex.EncodeToString(got) != *want {
					t.Errorf("encode(%q): got %x, want %s", in, got, *want)
				}
			}
			for i, h := range v.DecInputs {
				data, _ := hex.DecodeString(h)
				got, err := cptableDecode(c.Cp, data)
				want := c.Dec[i]
				if want == nil {
					if err == nil {
						t.Errorf("decode(%s): expected error, got %q", h, got)
					}
					continue
				}
				if err != nil {
					t.Errorf("decode(%s): unexpected error %v", h, err)
					continue
				}
				if got != *want {
					t.Errorf("decode(%s): got %q, want %q", h, got, *want)
				}
			}
			for _, rt := range c.Rt {
				got, err := cptableEncode(c.Cp, rt.S)
				if rt.H == nil {
					if err == nil {
						t.Errorf("rt encode(%q): expected error", rt.S)
					}
					continue
				}
				if err != nil || hex.EncodeToString(got) != *rt.H {
					t.Errorf("rt encode(%q): got %x/%v, want %s", rt.S, got, err, *rt.H)
					continue
				}
				back, derr := cptableDecode(c.Cp, got)
				if rt.Back == nil {
					if derr == nil {
						t.Errorf("rt decode(%q): expected error", rt.S)
					}
					continue
				}
				if derr != nil || back != *rt.Back {
					t.Errorf("rt decode(%s): got %q/%v, want %q", *rt.H, back, derr, *rt.Back)
				}
			}
		})
	}
}
