package ops

import (
	"strings"
	"testing"

	"github.com/roberson-io/cchef/internal/core"
)

// teaTS is a Hex-encoded toggle string for TEA/XTEA key and IV args.
func teaTS(v string) core.ToggleString { return core.ToggleString{Value: v, Option: "Hex"} }

// TestTEAFamily transcribes vectors generated by running CyberChef's
// lib/TEA.mjs directly (the CyberChef-server oracle predates these 2026
// operations, so the checked-out source is authoritative). Encrypt and decrypt
// cover both algorithms, all five modes, every padding, and custom XTEA rounds.
func TestTEAFamily(t *testing.T) {
	runCases(t, []opCase{
		{"TEA Encrypt ECB/PKCS5 5B", "48656c6c6f", "f10f02ef04402eab", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt ECB/PKCS5 8B", "0011223344556677", "37b83bfda90b8de383234447e5d31fc1", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt ECB/PKCS5 16B", "00112233445566778899aabbccddeeff", "37b83bfda90b8de3723c0e9bfe2962b083234447e5d31fc1", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt ECB/PKCS5 15B", "546865207175696b2062726f776e20", "8aab75522349813e89c6af7836d5a479", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CBC/PKCS5 5B", "48656c6c6f", "6bc39c762146ed50", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CBC/PKCS5 8B", "0011223344556677", "7d0cb1cb1392fbe889b94d9ed10a5e67", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CBC/PKCS5 16B", "00112233445566778899aabbccddeeff", "7d0cb1cb1392fbe86adb16ee632493ba36685d50daabb025", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CBC/PKCS5 15B", "546865207175696b2062726f776e20", "313736e3c9e6d72e66a08e8eeb65d014", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CFB/PKCS5 5B", "48656c6c6f", "832f19062b", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CFB/PKCS5 8B", "0011223344556677", "cb5b57590051fdde", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CFB/PKCS5 16B", "00112233445566778899aabbccddeeff", "cb5b57590051fdde8f8a11f49f376608", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CFB/PKCS5 15B", "546865207175696b2062726f776e20", "9f22104a3571f2c2f226dd270a683a", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt OFB/PKCS5 5B", "48656c6c6f", "832f19062b", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt OFB/PKCS5 8B", "0011223344556677", "cb5b57590051fdde", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt OFB/PKCS5 16B", "00112233445566778899aabbccddeeff", "cb5b57590051fddec99bd503808c4d0b", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt OFB/PKCS5 15B", "546865207175696b2062726f776e20", "9f22104a3571f2c261600dd73b3f83", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CTR/PKCS5 5B", "48656c6c6f", "832f19062b", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CTR/PKCS5 8B", "0011223344556677", "cb5b57590051fdde", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CTR/PKCS5 16B", "00112233445566778899aabbccddeeff", "cb5b57590051fdde94dc0efa01af1fab", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Encrypt CTR/PKCS5 15B", "546865207175696b2062726f776e20", "9f22104a3571f2c23c27d62eba1cd1", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5"}}}},
		{"XTEA Encrypt ECB/PKCS5 r32 5B", "48656c6c6f", "3de6ecaa388bb07d", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt ECB/PKCS5 r32 8B", "0011223344556677", "212b8a504ded884c35483e8ae392ddb7", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt ECB/PKCS5 r32 16B", "00112233445566778899aabbccddeeff", "212b8a504ded884c178e4057d2cc851e35483e8ae392ddb7", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt ECB/PKCS5 r32 15B", "546865207175696b2062726f776e20", "6e3ac57c944f6663750b3bedbea9bcf5", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CBC/PKCS5 r32 5B", "48656c6c6f", "0370bf92731e5b37", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CBC/PKCS5 r32 8B", "0011223344556677", "6c9162c9dae458d622df8a6ad208aa77", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CBC/PKCS5 r32 16B", "00112233445566778899aabbccddeeff", "6c9162c9dae458d6987c069d3c95e2734e4a9dd0e5857c49", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CBC/PKCS5 r32 15B", "546865207175696b2062726f776e20", "2a8b482cf0bbcae51ea67fa2cd6a8009", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CFB/PKCS5 r32 5B", "48656c6c6f", "8cdc134a5e", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CFB/PKCS5 r32 8B", "0011223344556677", "c4a85d1575c30a1a", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CFB/PKCS5 r32 16B", "00112233445566778899aabbccddeeff", "c4a85d1575c30a1ae34a56d9caa00a3b", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CFB/PKCS5 r32 15B", "546865207175696b2062726f776e20", "90d11a0640e305062d530b47cf7c3c", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt OFB/PKCS5 r32 5B", "48656c6c6f", "8cdc134a5e", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt OFB/PKCS5 r32 8B", "0011223344556677", "c4a85d1575c30a1a", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt OFB/PKCS5 r32 16B", "00112233445566778899aabbccddeeff", "c4a85d1575c30a1af86ae1d19f5c39ca", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt OFB/PKCS5 r32 15B", "546865207175696b2062726f776e20", "90d11a0640e305065091390524eff7", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CTR/PKCS5 r32 5B", "48656c6c6f", "8cdc134a5e", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CTR/PKCS5 r32 8B", "0011223344556677", "c4a85d1575c30a1a", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CTR/PKCS5 r32 16B", "00112233445566778899aabbccddeeff", "c4a85d1575c30a1a417577633b051604", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Encrypt CTR/PKCS5 r32 15B", "546865207175696b2062726f776e20", "90d11a0640e30506e98eafb780b6d8", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5", 32}}}},
		{"TEA Encrypt ECB/NO 8B", "0011223344556677", "f8f419b960ac3a11", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("0f1e2d3c4b5a69788796a5b4c3d2e1f0"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "NO"}}}},
		{"TEA Encrypt ECB/ZERO 5B", "48656c6c6f", "8c116da79e15c96c", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("0f1e2d3c4b5a69788796a5b4c3d2e1f0"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "ZERO"}}}},
		{"TEA Encrypt ECB/BIT 5B", "48656c6c6f", "7614ddf114720544", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("0f1e2d3c4b5a69788796a5b4c3d2e1f0"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "BIT"}}}},
		{"TEA Encrypt ECB/PKCS5 5B", "48656c6c6f", "81535aad2f7d7a9b", core.Recipe{{Op: "TEA Encrypt", Args: []any{teaTS("0f1e2d3c4b5a69788796a5b4c3d2e1f0"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5"}}}},
		{"XTEA Encrypt CBC/PKCS5 r1 10B", "48656c6c6f2c20544541", "6549ded5413e1116d8eac3ce517b5d84", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 1}}}},
		{"XTEA Encrypt CBC/PKCS5 r16 10B", "48656c6c6f2c20544541", "412c006416cccbb7f0485cd7afbea958", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 16}}}},
		{"XTEA Encrypt CBC/BIT r64 10B", "48656c6c6f2c20544541", "93d53339309b9d076456429aa07ac4c3", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "BIT", 64}}}},
		{"XTEA Encrypt CBC/PKCS5 r255 10B", "48656c6c6f2c20544541", "c921f483621c2bd5de4073016fb86960", core.Recipe{{Op: "XTEA Encrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5", 255}}}},
		{"TEA Decrypt ECB/PKCS5 8B", "f10f02ef04402eab", "48656c6c6f", core.Recipe{{Op: "TEA Decrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "ECB", "Hex", "Hex", "PKCS5"}}}},
		{"TEA Decrypt CBC/PKCS5 16B", "313736e3c9e6d72e66a08e8eeb65d014", "546865207175696b2062726f776e20", core.Recipe{{Op: "TEA Decrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "PKCS5"}}}},
		{"XTEA Decrypt CTR/PKCS5 r32 5B", "8cdc134a5e", "48656c6c6f", core.Recipe{{Op: "XTEA Decrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CTR", "Hex", "Hex", "PKCS5", 32}}}},
		{"XTEA Decrypt CBC/BIT r64 16B", "93d53339309b9d076456429aa07ac4c3", "48656c6c6f2c20544541", core.Recipe{{Op: "XTEA Decrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "CBC", "Hex", "Hex", "BIT", 64}}}},
		{"TEA Decrypt OFB/PKCS5 16B", "cb5b57590051fddec99bd503808c4d0b", "00112233445566778899aabbccddeeff", core.Recipe{{Op: "TEA Decrypt", Args: []any{teaTS("00112233445566778899aabbccddeeff"), teaTS("0001020304050607"), "OFB", "Hex", "Hex", "PKCS5"}}}},
	})
}

// TestTEAExtra covers the CFB decrypt path, Raw output, and empty input — cases
// not reached by the transcribed vectors. The decrypt values are the inverses of
// TestTEAFamily's CFB encrypt fixtures.
func TestTEAExtra(t *testing.T) {
	k := teaTS("00112233445566778899aabbccddeeff")
	iv := teaTS("0001020304050607")

	runCases(t, []opCase{
		// CFB decrypt (inverse of the "TEA Encrypt CFB/PKCS5 5B" fixture).
		{
			"TEA Decrypt CFB", "832f19062b", "48656c6c6f",
			core.Recipe{{Op: "TEA Decrypt", Args: []any{k, iv, "CFB", "Hex", "Hex", "PKCS5"}}},
		},
		// ECB ignores the IV, so an empty IV (defaulted to null bytes) matches the
		// non-empty-IV ECB fixture output.
		{
			"TEA Encrypt ECB empty IV", "48656c6c6f", "f10f02ef04402eab",
			core.Recipe{{Op: "TEA Encrypt", Args: []any{k, teaTS(""), "ECB", "Hex", "Hex", "PKCS5"}}},
		},
		{
			"XTEA Decrypt CFB", "8cdc134a5e", "48656c6c6f",
			core.Recipe{{Op: "XTEA Decrypt", Args: []any{k, iv, "CFB", "Hex", "Hex", "PKCS5", 32}}},
		},
	})

	// Raw output: decrypt recovers readable text.
	raw, err := runOp(t, "TEA Decrypt", "f10f02ef04402eab", k, iv, "ECB", "Hex", "Raw", "PKCS5")
	if err != nil || raw != "Hello" {
		t.Fatalf("raw output: got %q, err %v", raw, err)
	}

	// Empty input yields empty output for every operation.
	for _, op := range []string{"TEA Encrypt", "TEA Decrypt"} {
		out, err := runOp(t, op, "", k, iv, "ECB", "Raw", "Hex", "PKCS5")
		if err != nil || out != "" {
			t.Fatalf("%s empty: got %q, err %v", op, out, err)
		}
	}
	for _, op := range []string{"XTEA Encrypt", "XTEA Decrypt"} {
		out, err := runOp(t, op, "", k, iv, "ECB", "Raw", "Hex", "PKCS5", 32)
		if err != nil || out != "" {
			t.Fatalf("%s empty: got %q, err %v", op, out, err)
		}
	}
}

// TestTEAErrors covers the operations' validation error paths.
func TestTEAErrors(t *testing.T) {
	key16 := teaTS("00112233445566778899aabbccddeeff")
	iv8 := teaTS("0001020304050607")
	cases := []struct {
		name, op string
		key, iv  core.ToggleString
		mode     string
		padding  string
		extra    []any // rounds for XTEA
		input    string
		want     string
	}{
		{"TEA bad key length", "TEA Encrypt", teaTS("0011"), iv8, "CBC", "PKCS5", nil, "48656c6c6f", "Invalid key length: 2 bytes"},
		{"TEA bad IV length", "TEA Encrypt", key16, teaTS("0011"), "CBC", "PKCS5", nil, "48656c6c6f", "Invalid IV length: 2 bytes"},
		{"TEA NO padding partial", "TEA Encrypt", key16, iv8, "ECB", "NO", nil, "48656c6c6f", "No padding requested but input length (5 bytes) is not a multiple of 8 bytes."},
		{"TEA decrypt bad ct length", "TEA Decrypt", key16, iv8, "ECB", "PKCS5", nil, "0011223344", "Invalid ciphertext length: 5 bytes. Must be a multiple of 8."},
		{"TEA decrypt bad key", "TEA Decrypt", teaTS("0011"), iv8, "ECB", "PKCS5", nil, "0011223344556677", "Invalid key length: 2 bytes"},
		{"TEA decrypt bad PKCS5 padding", "TEA Decrypt", key16, iv8, "ECB", "PKCS5", nil, "0011223344556677", "Invalid PKCS#5 padding."},
		{"XTEA bad key length", "XTEA Encrypt", teaTS("0011"), iv8, "CBC", "PKCS5", []any{32}, "48656c6c6f", "Invalid key length: 2 bytes"},
		{"XTEA rounds too low", "XTEA Encrypt", key16, iv8, "CBC", "PKCS5", []any{0}, "48656c6c6f", "Invalid number of rounds: 0"},
		{"XTEA rounds too high", "XTEA Encrypt", key16, iv8, "CBC", "PKCS5", []any{256}, "48656c6c6f", "Invalid number of rounds: 256"},
		{"XTEA rounds non-integer", "XTEA Encrypt", key16, iv8, "CBC", "PKCS5", []any{32.5}, "48656c6c6f", "Invalid number of rounds: 32.5"},
		{"XTEA decrypt rounds too low", "XTEA Decrypt", key16, iv8, "CBC", "PKCS5", []any{0}, "0011223344556677", "Invalid number of rounds: 0"},
		{"XTEA decrypt bad key", "XTEA Decrypt", teaTS("0011"), iv8, "CBC", "PKCS5", []any{32}, "0011223344556677", "Invalid key length: 2 bytes"},
		{"XTEA decrypt bad ct length", "XTEA Decrypt", key16, iv8, "ECB", "PKCS5", []any{32}, "0011223344", "Invalid ciphertext length: 5 bytes"},
		{"XTEA encrypt NO padding partial", "XTEA Encrypt", key16, iv8, "ECB", "NO", []any{32}, "48656c6c6f", "No padding requested but input length (5 bytes)"},
		{"TEA bad base64 key", "TEA Encrypt", core.ToggleString{Value: "!!!", Option: "Base64"}, iv8, "CBC", "PKCS5", nil, "48656c6c6f", ""},
		{"TEA bad base64 IV", "TEA Encrypt", key16, core.ToggleString{Value: "!!!", Option: "Base64"}, "CBC", "PKCS5", nil, "48656c6c6f", ""},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			args := append([]any{c.key, c.iv, c.mode, "Hex", "Hex", c.padding}, c.extra...)
			_, err := runOp(t, c.op, c.input, args...)
			if err == nil {
				t.Fatalf("expected error")
			}
			if c.want != "" && !strings.Contains(err.Error(), c.want) {
				t.Fatalf("got %q, want substring %q", err.Error(), c.want)
			}
		})
	}
}
