package ops

import (
	"testing"

	"github.com/dlclark/regexp2"

	"github.com/roberson-io/cchef/internal/core"
)

// TestParseUserAgentVectors is a differential test against ua-parser-js 2.0.10
// (the exact version the CyberChef-server oracle uses), covering diverse
// browsers, engines, OSes, CPUs and the device table (many vendors/models).
// Expected outputs were generated by running each UA through the genuine library.
func TestParseUserAgentVectors(t *testing.T) {
	runCases(t, []opCase{
		{
			"ua 0", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0.0.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 1", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Safari/605.1.15", `Browser
    Name: Safari
    Version: 17.1
Device
    Model: Macintosh
    Type: unknown
    Vendor: Apple
Engine
    Name: WebKit
    Version: 605.1.15
OS
    Name: macOS
    Version: 10.15.7
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 2", "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:121.0) Gecko/20100101 Firefox/121.0", `Browser
    Name: Firefox
    Version: 121.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Gecko
    Version: 121.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 3", "Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1", `Browser
    Name: Mobile Safari
    Version: 17.0
Device
    Model: iPhone
    Type: mobile
    Vendor: Apple
Engine
    Name: WebKit
    Version: 605.1.15
OS
    Name: iOS
    Version: 17.0
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 4", "Mozilla/5.0 (Linux; Android 13; Pixel 7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 120.0.0.0
Device
    Model: Pixel 7
    Type: mobile
    Vendor: Google
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 5", "Mozilla/5.0 (Linux; Android 13; SM-S918B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 119.0.0.0
Device
    Model: SM-S918B
    Type: mobile
    Vendor: Samsung
Engine
    Name: Blink
    Version: 119.0.0.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 6", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0", `Browser
    Name: Edge
    Version: 120.0.0.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 7", "Opera/9.80 (Windows NT 6.0) Presto/2.12.388 Version/12.14", `Browser
    Name: Opera
    Version: 12.14
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Presto
    Version: 2.12.388
OS
    Name: Windows
    Version: Vista
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 8", "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0", `Browser
    Name: Opera
    Version: 105.0.0.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 119.0.0.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 9", "Mozilla/5.0 (iPad; CPU OS 17_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.1 Mobile/15E148 Safari/604.1", `Browser
    Name: Mobile Safari
    Version: 17.1
Device
    Model: iPad
    Type: tablet
    Vendor: Apple
Engine
    Name: WebKit
    Version: 605.1.15
OS
    Name: iOS
    Version: 17.1
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 10", "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0.0.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Linux
    Version: unknown
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 11", "Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)", `Browser
    Name: unknown
    Version: unknown
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 12", "curl/8.4.0", `Browser
    Name: unknown
    Version: unknown
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 13", "Wget/1.21.3", `Browser
    Name: unknown
    Version: unknown
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 14", "Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko", `Browser
    Name: IE
    Version: 11.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Trident
    Version: 7.0
OS
    Name: Windows
    Version: 7
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 15", "Mozilla/5.0 (Linux; U; Android 4.4.2; en-us; SCH-I535 Build/KOT49H) AppleWebKit/534.30 (KHTML, like Gecko) Version/4.0 Mobile Safari/534.30", `Browser
    Name: Android Browser
    Version: 4.0
Device
    Model: SCH-I535
    Type: mobile
    Vendor: Samsung
Engine
    Name: WebKit
    Version: 534.30
OS
    Name: Android
    Version: 4.4.2
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 16", "Mozilla/5.0 (PlayStation 5 2.26) AppleWebKit/605.1.15 (KHTML, like Gecko)", `Browser
    Name: WebKit
    Version: 605.1.15
Device
    Model: PlayStation 5
    Type: console
    Vendor: Sony
Engine
    Name: WebKit
    Version: 605.1.15
OS
    Name: PlayStation
    Version: 5
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 17", "Mozilla/5.0 (Windows Phone 10.0; Android 6.0.1; Microsoft; Lumia 950) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Mobile Safari/537.36 Edge/15.15254", `Browser
    Name: Edge
    Version: 15.15254
Device
    Model: Lumia 950
    Type: mobile
    Vendor: Microsoft
Engine
    Name: EdgeHTML
    Version: 15.15254
OS
    Name: Windows Phone
    Version: 10.0
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 18", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0", `Browser
    Name: Firefox
    Version: 120.0
Device
    Model: Macintosh
    Type: unknown
    Vendor: Apple
Engine
    Name: Gecko
    Version: 120.0
OS
    Name: macOS
    Version: 10.15
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 19", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 120.0.0.0
Device
    Model: K
    Type: mobile
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 10
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 20", "Mozilla/5.0 (Linux; Android 14; SM-S928B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 121.0.0.0
Device
    Model: SM-S928B
    Type: mobile
    Vendor: Samsung
Engine
    Name: Blink
    Version: 121.0.0.0
OS
    Name: Android
    Version: 14
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 21", "Mozilla/5.0 (Linux; Android 13; 2201123G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 120.0.0.0
Device
    Model: 2201123G
    Type: mobile
    Vendor: Xiaomi
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 22", "Mozilla/5.0 (Linux; Android 12; CPH2451) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 119.0.0.0
Device
    Model: CPH2451
    Type: mobile
    Vendor: OnePlus
Engine
    Name: Blink
    Version: 119.0.0.0
OS
    Name: Android
    Version: 12
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 23", "Mozilla/5.0 (Linux; Android 13; V2145) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 118.0.0.0
Device
    Model: V2145
    Type: mobile
    Vendor: unknown
Engine
    Name: Blink
    Version: 118.0.0.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 24", "Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 117.0
Device
    Model: Redmi Note 8 Pro
    Type: mobile
    Vendor: Xiaomi
Engine
    Name: Blink
    Version: 117.0
OS
    Name: Android
    Version: 11
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 25", "Mozilla/5.0 (Linux; Android 10; HUAWEI VOG-L29) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 116.0
Device
    Model: VOG-L29
    Type: mobile
    Vendor: Huawei
Engine
    Name: Blink
    Version: 116.0
OS
    Name: Android
    Version: 10
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 26", "Mozilla/5.0 (Linux; Android 13; motorola edge 30) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 115.0
Device
    Model: edge 30
    Type: mobile
    Vendor: Motorola
Engine
    Name: Blink
    Version: 115.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 27", "Mozilla/5.0 (Linux; Android 12; LM-G900) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 114.0
Device
    Model: LM-G900
    Type: mobile
    Vendor: LG
Engine
    Name: Blink
    Version: 114.0
OS
    Name: Android
    Version: 12
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 28", "Mozilla/5.0 (Linux; Android 13; Nokia G50) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 113.0
Device
    Model: G50
    Type: mobile
    Vendor: Nokia
Engine
    Name: Blink
    Version: 113.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 29", "Mozilla/5.0 (Linux; Android 12; SAMSUNG SM-T870) AppleWebKit/537.36 (KHTML, like Gecko) SamsungBrowser/23.0 Chrome/115.0.0.0 Safari/537.36", `Browser
    Name: Samsung Internet
    Version: 23.0
Device
    Model: SM-T870
    Type: tablet
    Vendor: Samsung
Engine
    Name: Blink
    Version: 115.0.0.0
OS
    Name: Android
    Version: 12
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 30", "Mozilla/5.0 (Linux; Android 13; SM-A536B) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Mobile DuckDuckGo/5 Safari/537.36", `Browser
    Name: DuckDuckGo
    Version: 5
Device
    Model: SM-A536B
    Type: mobile
    Vendor: Samsung
Engine
    Name: Blink
    Version: 120.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 31", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Brave/120", `Browser
    Name: Brave
    Version: 120
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 32", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 Vivaldi/6.5", `Browser
    Name: Vivaldi
    Version: 6.5
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 119.0.0.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 33", "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0.0.0
Device
    Model: Macintosh
    Type: unknown
    Vendor: Apple
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: macOS
    Version: 10.15.7
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 34", "Mozilla/5.0 (Linux; U; Android 9; SM-G960F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0 Mobile Safari/537.36 [FB_IAB/FB4A;FBAV/300.0]", `Browser
    Name: Chrome WebView
    Version: 74.0
Device
    Model: SM-G960F
    Type: mobile
    Vendor: Samsung
Engine
    Name: Blink
    Version: 74.0
OS
    Name: Android
    Version: 9
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 35", "Mozilla/5.0 (iPhone; CPU iPhone OS 16_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/120.0.0.0 Mobile/15E148 Safari/604.1", `Browser
    Name: Mobile Chrome
    Version: 120.0.0.0
Device
    Model: iPhone
    Type: mobile
    Vendor: Apple
Engine
    Name: WebKit
    Version: 605.1.15
OS
    Name: iOS
    Version: 16.6
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 36", "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 YaBrowser/24.1 Safari/537.36", `Browser
    Name: Yandex
    Version: 24.1
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Windows
    Version: 10
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 37", "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36 EdgA/120.0.0.0", `Browser
    Name: Edge
    Version: 120.0.0.0
Device
    Model: K
    Type: mobile
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 10
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 38", "Mozilla/5.0 (SMART-TV; Linux; Tizen 6.0) AppleWebKit/537.36 (KHTML, like Gecko) 76.0.3809.146 TV Safari/537.36", `Browser
    Name: Safari
    Version: 1
Device
    Model: unknown
    Type: smarttv
    Vendor: unknown
Engine
    Name: WebKit
    Version: 537.36
OS
    Name: Tizen
    Version: 6.0
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 39", "Mozilla/5.0 (Web0S; Linux/SmartTV) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0 Safari/537.36 WebAppManager", `Browser
    Name: Chrome
    Version: 94.0
Device
    Model: unknown
    Type: smarttv
    Vendor: unknown
Engine
    Name: Blink
    Version: 94.0
OS
    Name: webOS
    Version: 23
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 40", "Roku/DVP-9.10 (289.10E04170A)", `Browser
    Name: unknown
    Version: unknown
Device
    Model: DVP-9.10
    Type: smarttv
    Vendor: Roku
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 41", "Mozilla/5.0 (Nintendo Switch; WifiWebAuthApplet) AppleWebKit/609.4 (KHTML, like Gecko) NF/6.0.2.21.3 NintendoBrowser/5.1.0.22433", `Browser
    Name: WebKit
    Version: 609.4
Device
    Model: Switch
    Type: console
    Vendor: Nintendo
Engine
    Name: WebKit
    Version: 609.4
OS
    Name: Nintendo
    Version: Switch
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 42", "Mozilla/5.0 (X11; CrOS x86_64 14541.0.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0.0.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Chrome OS
    Version: 14541.0.0
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 43", "Mozilla/5.0 (Linux; Android 13; Pixel Tablet) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0
Device
    Model: Pixel Tablet
    Type: tablet
    Vendor: Google
Engine
    Name: Blink
    Version: 120.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 44", "facebookexternalhit/1.1 (+http://www.facebook.com/externalhit_uatext.php)", `Browser
    Name: unknown
    Version: unknown
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 45", "Mozilla/5.0 (compatible; bingbot/2.0; +http://www.bing.com/bingbot.htm)", `Browser
    Name: unknown
    Version: unknown
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 46", "python-requests/2.31.0", `Browser
    Name: unknown
    Version: unknown
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: unknown
    Version: unknown
OS
    Name: unknown
    Version: unknown
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 47", "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Blink
    Version: 120.0
OS
    Name: Windows
    Version: 8.1
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 48", "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:40.0) Gecko/20100101 Firefox/40.0", `Browser
    Name: Firefox
    Version: 40.0
Device
    Model: unknown
    Type: unknown
    Vendor: unknown
Engine
    Name: Gecko
    Version: 40.0
OS
    Name: Windows
    Version: 7
CPU
    Architecture: amd64`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		{
			"ua 49", "Mozilla/5.0 (iPad; CPU OS 15_7 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/121.0 Mobile/15E148 Safari/605.1.15", `Browser
    Name: Mobile Firefox
    Version: 121.0
Device
    Model: iPad
    Type: tablet
    Vendor: Apple
Engine
    Name: WebKit
    Version: 605.1.15
OS
    Name: iOS
    Version: 15.7
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		// T-Mobile REVVL devices classify device type via strTest (regex "ta?b" on
		// the model): no "tab" -> mobile (uaStrTest ifFalse branch).
		{
			"ua 50 (strTest mobile)", "Mozilla/5.0 (Linux; Android 12; REVVL 6 5G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 120.0.0.0
Device
    Model: REVVL 6 5G
    Type: mobile
    Vendor: T-Mobile
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 12
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		// ...and a model containing "TAB" -> tablet (uaStrTest ifTrue branch).
		{
			"ua 51 (strTest tablet)", "Mozilla/5.0 (Linux; Android 12; REVVL TAB 5G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0.0.0
Device
    Model: REVVL TAB 5G
    Type: tablet
    Vendor: T-Mobile
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 12
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		// An OPD2 model not in the OnePlus id list falls through strMapper's "*"
		// entry to the OPPO vendor (uaStrMapper's hasStar branch).
		{
			"ua 52 (strMapper star)", "Mozilla/5.0 (Linux; Android 13; OPD2202) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36", `Browser
    Name: Chrome
    Version: 120.0.0.0
Device
    Model: OPD2202
    Type: tablet
    Vendor: OPPO
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 13
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		// An Itel device exercises the "lowerize" function processor on the vendor.
		{
			"ua 53 (lowerize fn)", "Mozilla/5.0 (Linux; Android 11; itel A661W) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Mobile Safari/537.36", `Browser
    Name: Mobile Chrome
    Version: 120.0.0.0
Device
    Model: A661W
    Type: mobile
    Vendor: itel
Engine
    Name: Blink
    Version: 120.0.0.0
OS
    Name: Android
    Version: 11
CPU
    Architecture: unknown`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
		// A PowerPC Mac exercises the "lowerize" processor in a replace rule (the
		// CPU architecture is rewritten "powerpc" -> "ppc" and lower-cased).
		{
			"ua 54 (replace lowerize)", "Mozilla/5.0 (Macintosh; PPC Mac OS X 10_5_8) AppleWebKit/533.19.4 (KHTML, like Gecko) Version/5.0.3 Safari/533.19.4", `Browser
    Name: Safari
    Version: 5.0.3
Device
    Model: Macintosh
    Type: unknown
    Vendor: Apple
Engine
    Name: WebKit
    Version: 533.19.4
OS
    Name: macOS
    Version: 10.5.8
CPU
    Architecture: ppc`,
			core.Recipe{{Op: "Parse User Agent", Args: []any{}}},
		},
	})
}

// TestUAStrMapperEngineBranches exercises the strMapper semantics the current
// ruleset doesn't use: an undef entry is skipped, a "?" key means UNKNOWN, and a
// "*" fallback mapped to undefined also reports not-found.
func TestUAStrMapperEngineBranches(t *testing.T) {
	skip := &uaLookup{entries: []uaLookupEntry{
		{undef: true, vals: []string{"a"}},
		{key: "Match", vals: []string{"a"}},
	}}
	if got, ok := uaStrMapper("a", skip); !ok || got != "Match" {
		t.Fatalf("undef skip: got %q, %v; want Match, true", got, ok)
	}
	unknown := &uaLookup{entries: []uaLookupEntry{{key: "?", vals: []string{"a"}}}}
	if got, ok := uaStrMapper("a", unknown); ok || got != "" {
		t.Fatalf(`"?" key: got %q, %v; want "", false`, got, ok)
	}
	starUndef := &uaLookup{hasStar: true, star: "ignored", starUndef: true}
	if got, ok := uaStrMapper("no-match", starUndef); ok || got != "" {
		t.Fatalf("starUndef: got %q, %v; want \"\", false", got, ok)
	}
}

// TestUAApplyPropsEngineBranches exercises the property-processing arms the ruleset
// doesn't reach: empty-capture deletes (strTest/strMapper/replace), a strMapper
// "unknown" result deleting the property, and the replace "trim" processor.
func TestUAApplyPropsEngineBranches(t *testing.T) {
	rx := func(p string) *regexp2.Regexp { return regexp2.MustCompile(p, regexp2.None) }
	unknownMap := &uaLookup{entries: []uaLookupEntry{{key: "?", vals: []string{"x"}}}}

	cases := []struct {
		name      string
		props     []uaProp
		matched   []string
		wantValue string // "" => the property must be deleted
	}{
		{
			"strTest empty capture deletes",
			[]uaProp{{prop: "p", kind: "fn", fn: "strTest", testRe: rx("t"), ifTrue: "a", ifFalse: "b"}},
			[]string{"full"},
			"",
		},
		{
			"strMapper empty capture deletes",
			[]uaProp{{prop: "p", kind: "fn", fn: "strMapper", fnMap: unknownMap}},
			[]string{"full"},
			"",
		},
		{
			"strMapper unknown value deletes",
			[]uaProp{{prop: "p", kind: "fn", fn: "strMapper", fnMap: unknownMap}},
			[]string{"full", "x"},
			"",
		},
		{
			"replace trim",
			[]uaProp{{prop: "p", kind: "replace", replRe: rx("Z"), repl: "", replFn: "trim"}},
			[]string{"full", "  abc"},
			"abc",
		},
		{
			"replace strMapper unknown value deletes",
			[]uaProp{{prop: "p", kind: "replace", replRe: rx("Z"), repl: "", replFn: "strMapper", replMap: unknownMap}},
			[]string{"full", "x"},
			"",
		},
		{
			"replace empty capture deletes",
			[]uaProp{{prop: "p", kind: "replace", replRe: rx("Z"), repl: ""}},
			[]string{"full"},
			"",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			res := map[string]string{"p": "preset"}
			uaApplyProps(res, c.props, c.matched)
			got, ok := res["p"]
			if c.wantValue == "" {
				if ok {
					t.Fatalf("expected property deleted, got %q", got)
				}
			} else if got != c.wantValue {
				t.Fatalf("got %q, want %q", got, c.wantValue)
			}
		})
	}
}
