//go:build ignore

// Command magicgen generates internal/ops/magic_data.go from the tables
// previously extracted from CyberChef to magicdata.json by dump.mjs.
//
// Run from the repository root:
//
//	go run tools/magicgen/gen.go
//
// See tools/magicgen/README.md for how to refresh magicdata.json.
package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"log"
	"os"
	"sort"
	"strconv"
)

type outputCriteria struct {
	Pattern      string    `json:"pattern"`
	Flags        string    `json:"flags"`
	EntropyRange []float64 `json:"entropyRange"`
	Mime         string    `json:"mime"`
}

type check struct {
	Op           string          `json:"op"`
	Pattern      string          `json:"pattern"`
	Flags        string          `json:"flags"`
	Args         []any           `json:"args"`
	Useful       bool            `json:"useful"`
	EntropyRange []float64       `json:"entropyRange"`
	Output       *outputCriteria `json:"output"`
}

type data struct {
	Checks         []check              `json:"checks"`
	CommonLangs    map[string][]float64 `json:"commonLangs"`
	ExtensiveLangs map[string][]float64 `json:"extensiveLangs"`
	LanguageNames  map[string]string    `json:"languageNames"`
}

// goArg renders one argument value from a check as Go source. Only the shapes
// CyberChef's checks actually use appear here; anything else stops the build
// rather than being quietly mistranslated.
func goArg(v any) string {
	switch x := v.(type) {
	case string:
		return strconv.Quote(x)
	case bool:
		return strconv.FormatBool(x)
	case float64:
		if x == float64(int64(x)) {
			return fmt.Sprintf("%d.0", int64(x))
		}
		return strconv.FormatFloat(x, 'g', -1, 64)
	case nil:
		return "nil"
	case map[string]any:
		// A toggle string, written as {option, string}.
		opt, _ := x["option"].(string)
		str, _ := x["string"].(string)
		return fmt.Sprintf("core.ToggleString{Value: %s, Option: %s}",
			strconv.Quote(str), strconv.Quote(opt))
	case []any:
		// One check gives an option argument the whole list of choices rather
		// than one of them. Upstream looks that list up as if it were a single
		// choice, finds nothing, and falls back to the operation's default,
		// which is the first choice — so that is what it means here.
		if len(x) == 0 {
			log.Fatal("empty argument list")
		}
		return goArg(x[0])
	}
	log.Fatalf("unsupported argument %#v", v)
	return ""
}

// goRange renders an entropy range, which is either absent or a pair.
func goRange(r []float64) string {
	if len(r) != 2 {
		return "nil"
	}
	return fmt.Sprintf("[]float64{%v, %v}", r[0], r[1])
}

func main() {
	raw, err := os.ReadFile("tools/magicgen/magicdata.json")
	if err != nil {
		log.Fatal(err)
	}
	var d data
	if err := json.Unmarshal(raw, &d); err != nil {
		log.Fatal(err)
	}

	// Only checks carrying a toggle-string argument need the core package.
	needsCore := false
	for _, c := range d.Checks {
		for _, a := range c.Args {
			if _, ok := a.(map[string]any); ok {
				needsCore = true
			}
		}
	}
	coreImport := ""
	if needsCore {
		coreImport = "\nimport \"github.com/roberson-io/cchef/internal/core\"\n"
	}

	var b bytes.Buffer
	fmt.Fprintf(&b, `// Code generated by tools/magicgen/gen.go; DO NOT EDIT.

package ops
%s
// magicChecks is what every operation claims it can decode: a pattern the data
// must match, an entropy range it must fall in, or both, along with the
// arguments to run the operation with. Extracted from CyberChef's
// OperationConfig.json (%d checks over the operations that declare them).
var magicChecks = []magicCheck{
`, coreImport, len(d.Checks))

	for _, c := range d.Checks {
		fmt.Fprintf(&b, "\t{\n\t\tOp: %s,\n", strconv.Quote(c.Op))
		if c.Pattern != "" {
			fmt.Fprintf(&b, "\t\tPattern: %s,\n", strconv.Quote(magicGoPattern(c.Pattern, c.Flags)))
		}
		if len(c.Args) > 0 {
			fmt.Fprint(&b, "\t\tArgs: []any{")
			for i, a := range c.Args {
				if i > 0 {
					fmt.Fprint(&b, ", ")
				}
				fmt.Fprint(&b, goArg(a))
			}
			fmt.Fprint(&b, "},\n")
		}
		if c.Useful {
			fmt.Fprint(&b, "\t\tUseful: true,\n")
		}
		if r := goRange(c.EntropyRange); r != "nil" {
			fmt.Fprintf(&b, "\t\tEntropyRange: %s,\n", r)
		}
		if c.Output != nil {
			fmt.Fprint(&b, "\t\tOutput: &magicOutputCheck{\n")
			if c.Output.Pattern != "" {
				fmt.Fprintf(&b, "\t\t\tPattern: %s,\n",
					strconv.Quote(magicGoPattern(c.Output.Pattern, c.Output.Flags)))
			}
			if r := goRange(c.Output.EntropyRange); r != "nil" {
				fmt.Fprintf(&b, "\t\t\tEntropyRange: %s,\n", r)
			}
			if c.Output.Mime != "" {
				fmt.Fprintf(&b, "\t\t\tMime: %s,\n", strconv.Quote(c.Output.Mime))
			}
			fmt.Fprint(&b, "\t\t},\n")
		}
		fmt.Fprint(&b, "\t},\n")
	}
	fmt.Fprint(&b, "}\n\n")

	writeLangs(&b, "magicCommonLangs",
		"magicCommonLangs holds the byte-frequency profile of each of the languages\n// most used on the Internet, as a percentage per byte value.",
		d.CommonLangs)
	writeLangs(&b, "magicExtensiveLangs",
		"magicExtensiveLangs holds the same profiles for a much wider set of\n// languages, which the operation compares against when asked to.",
		d.ExtensiveLangs)

	fmt.Fprint(&b, "// magicLanguageNames gives the name of each language code.\nvar magicLanguageNames = map[string]string{\n")
	codes := make([]string, 0, len(d.LanguageNames))
	for code := range d.LanguageNames {
		codes = append(codes, code)
	}
	sort.Strings(codes)
	for _, code := range codes {
		fmt.Fprintf(&b, "\t%s: %s,\n", strconv.Quote(code), strconv.Quote(d.LanguageNames[code]))
	}
	fmt.Fprint(&b, "}\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatalf("format: %v", err)
	}
	if err := os.WriteFile("internal/ops/magic_data.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("wrote internal/ops/magic_data.go: %d checks, %d common and %d extensive languages\n",
		len(d.Checks), len(d.CommonLangs), len(d.ExtensiveLangs))
}

// writeLangs emits one language frequency table, sorted by code so the
// generated file is stable.
func writeLangs(b *bytes.Buffer, name, doc string, langs map[string][]float64) {
	fmt.Fprintf(b, "// %s\nvar %s = map[string][256]float64{\n", doc, name)
	codes := make([]string, 0, len(langs))
	for code := range langs {
		codes = append(codes, code)
	}
	sort.Strings(codes)
	for _, code := range codes {
		freqs := langs[code]
		if len(freqs) != 256 {
			log.Fatalf("%s: %d frequencies, want 256", code, len(freqs))
		}
		fmt.Fprintf(b, "\t%s: {", strconv.Quote(code))
		for i, f := range freqs {
			if i > 0 {
				fmt.Fprint(b, ", ")
			}
			fmt.Fprint(b, strconv.FormatFloat(f, 'g', -1, 64))
		}
		fmt.Fprint(b, "},\n")
	}
	fmt.Fprint(b, "}\n\n")
}

// magicGoPattern turns a JavaScript pattern and its flags into one Go pattern.
// The global flag has no meaning for a match test and is dropped; the rest map
// onto Go's inline flags.
func magicGoPattern(pattern, flags string) string {
	inline := ""
	for _, f := range flags {
		switch f {
		case 'i':
			inline += "i"
		case 'm':
			inline += "m"
		case 's':
			inline += "s"
		}
	}
	if inline == "" {
		return pattern
	}
	return "(?" + inline + ")" + pattern
}
