package ops

import (
	"testing"

	"github.com/roberson-io/cchef/core"
)

// Vectors derived from the CyberChef-server oracle (Analyse hash has no upstream
// operation fixtures). They cover a known length (map hit), an unknown length
// (default), a fractional byte length (odd input), and the invalid-hash error.
func TestAnalyseHashFixtures(t *testing.T) {
	head := func(length, bits, byteLen string) string {
		return "Hash length: " + length + "\nByte length: " + byteLen +
			"\nBit length:  " + bits + "\n\n" +
			"Based on the length, this hash could have been generated by one of the following hashing functions:\n"
	}
	runCases(t, []opCase{
		{
			"Analyse hash: CRC-16 length", "abcd",
			head("4", "16", "2") + "BSD checksum\nCRC-16\nSYSV checksum\nFletcher-16",
			core.Recipe{{Op: "Analyse hash", Args: []any{}}},
		},
		{
			"Analyse hash: MD5 length", "d41d8cd98f00b204e9800998ecf8427e",
			head("32", "128", "16") + "MD5\nMD4\nMD2\nHAVAL-128\nRIPEMD-128\nSnefru\nTiger-128",
			core.Recipe{{Op: "Analyse hash", Args: []any{}}},
		},
		{
			"Analyse hash: SHA-256 length (non-ASCII name)", "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
			head("64", "256", "32") + "SHA-256\nSHA3-256\nBLAKE-256\nECOH-256\nFSB-256\nGOST\nGrøstl-256\nHAVAL-256\nPANAMA\nRIPEMD-256\nSnefru",
			core.Recipe{{Op: "Analyse hash", Args: []any{}}},
		},
		{
			"Analyse hash: unknown length", "abcdef0123",
			head("10", "40", "5") + "Unknown",
			core.Recipe{{Op: "Analyse hash", Args: []any{}}},
		},
		{
			"Analyse hash: odd length (fractional bytes)", "abcde",
			head("5", "20", "2.5") + "Unknown",
			core.Recipe{{Op: "Analyse hash", Args: []any{}}},
		},
		{
			"Analyse hash: whitespace is stripped", "ab cd",
			head("4", "16", "2") + "BSD checksum\nCRC-16\nSYSV checksum\nFletcher-16",
			core.Recipe{{Op: "Analyse hash", Args: []any{}}},
		},
	})
}

func TestAnalyseHashInvalid(t *testing.T) {
	for _, in := range []string{"xyz", ""} {
		if _, err := runOp(t, "Analyse hash", in); err == nil || err.Error() != "Invalid hash" {
			t.Fatalf("input %q: got %v, want Invalid hash", in, err)
		}
	}
}
