package ops

import (
	"errors"
	"regexp"
	"strconv"
	"strings"

	"github.com/roberson-io/cchef/core"
)

func init() {
	core.Register(AnalyseHash{})
}

// analyseHashHexRe matches a non-empty run of hex digits (case-insensitive).
var analyseHashHexRe = regexp.MustCompile(`^[a-fA-F0-9]+$`)

// analyseHashFunctions maps a hash's bit length to the functions known to
// produce a digest of that size, transcribed from CyberChef's AnalyseHash.
var analyseHashFunctions = map[int][]string{
	4:    {"Fletcher-4", "Luhn algorithm", "Verhoeff algorithm"},
	8:    {"Fletcher-8"},
	16:   {"BSD checksum", "CRC-16", "SYSV checksum", "Fletcher-16"},
	32:   {"CRC-32", "Fletcher-32", "Adler-32"},
	64:   {"CRC-64", "RIPEMD-64", "SipHash"},
	128:  {"MD5", "MD4", "MD2", "HAVAL-128", "RIPEMD-128", "Snefru", "Tiger-128"},
	160:  {"SHA-1", "SHA-0", "FSB-160", "HAS-160", "HAVAL-160", "RIPEMD-160", "Tiger-160"},
	192:  {"Tiger", "HAVAL-192"},
	224:  {"SHA-224", "SHA3-224", "ECOH-224", "FSB-224", "HAVAL-224"},
	256:  {"SHA-256", "SHA3-256", "BLAKE-256", "ECOH-256", "FSB-256", "GOST", "Grøstl-256", "HAVAL-256", "PANAMA", "RIPEMD-256", "Snefru"},
	320:  {"RIPEMD-320"},
	384:  {"SHA-384", "SHA3-384", "ECOH-384", "FSB-384"},
	512:  {"SHA-512", "SHA3-512", "BLAKE-512", "ECOH-512", "FSB-512", "Grøstl-512", "JH", "MD6", "Spectral Hash", "SWIFFT", "Whirlpool"},
	1024: {"Fowler-Noll-Vo"},
}

// AnalyseHash guesses which hashing functions could have produced a given hash,
// based on its length.
type AnalyseHash struct{}

// Meta returns the operation metadata.
func (AnalyseHash) Meta() core.OpMeta {
	return core.OpMeta{
		Name:        "Analyse hash",
		Module:      "Crypto",
		Description: "Tries to determine information about a given hash and suggests which algorithm may have been used to generate it based on its length.",
		InfoURL:     "https://wikipedia.org/wiki/Comparison_of_cryptographic_hash_functions",
		InputType:   core.TypeString,
		OutputType:  core.TypeString,
	}
}

// Args returns the argument definitions.
func (AnalyseHash) Args() []core.ArgDef { return nil }

// Run reports the hash's length and the candidate hashing functions.
func (AnalyseHash) Run(in *core.Dish, _ []any) (*core.Dish, error) {
	input := stripWhitespace(in.String())
	if !analyseHashHexRe.MatchString(input) {
		//nolint:staticcheck,revive // verbatim CyberChef OperationError text
		return nil, errors.New("Invalid hash")
	}

	length := len(input)
	bitLength := length * 4
	functions, ok := analyseHashFunctions[bitLength]
	if !ok {
		functions = []string{"Unknown"}
	}

	var out strings.Builder
	out.WriteString("Hash length: " + strconv.Itoa(length) + "\n")
	out.WriteString("Byte length: " + strconv.FormatFloat(float64(length)/2, 'f', -1, 64) + "\n")
	out.WriteString("Bit length:  " + strconv.Itoa(bitLength) + "\n\n")
	out.WriteString("Based on the length, this hash could have been generated by one of the following hashing functions:\n")
	out.WriteString(strings.Join(functions, "\n"))
	return core.NewDish([]byte(out.String()), core.TypeString), nil
}
