package ops

import (
	"testing"

	"github.com/roberson-io/cchef/core"
)

// sigabaRecipe builds a SIGABA recipe from the 41 ordered arguments.
func sigabaRecipe(args ...any) core.Recipe {
	return core.Recipe{{Op: "SIGABA", Args: args}}
}

// sigabaDefaultArgs returns the 41 args using the Example-1 rotors (all initial
// A / 0, none reversed) and the given mode.
func sigabaDefaultArgs(mode string) []any {
	const cr = "SRGWANHPJZFXVIDQCEUKBYOLMT"
	const ir = "6201348957"
	args := make([]any, 0, 41)
	for range 10 {
		args = append(args, cr, false, "A")
	}
	for range 5 {
		args = append(args, ir, "0")
	}
	return append(args, mode)
}

// TestSIGABADefaultRotors covers lowercase and space handling (oracle-verified):
// input is upper-cased before encryption and spaces are preserved.
func TestSIGABADefaultRotors(t *testing.T) {
	runCases(t, []opCase{
		{
			"lowercase + spaces", "attack at dawn", "ECBJFETMJZMAUX",
			sigabaRecipe(sigabaDefaultArgs("Encrypt")...),
		},
	})
}

// TestSIGABAOutOfRange covers non-A-Z input: like CyberChef, each such character
// enciphers to "@" (the JS out-of-bounds cascade) rather than panicking.
func TestSIGABAOutOfRange(t *testing.T) {
	runCases(t, []opCase{
		{"digit tail", "HELLO1", "HIPGI@", sigabaRecipe(sigabaDefaultArgs("Encrypt")...)},
		{"all digits", "12345", "@@@@@", sigabaRecipe(sigabaDefaultArgs("Encrypt")...)},
	})
}

// TestSIGABARoundTrip encrypts then decrypts with identical settings; the input
// is recovered (exercising the space<->Z conversion on both paths). Literal "Z"
// is deliberately avoided as it maps to "X" and is not recoverable.
func TestSIGABARoundTrip(t *testing.T) {
	input := "MEET AT THE BRIDGE AT NOON"
	ct, err := core.Recipe{{Op: "SIGABA", Args: sigabaDefaultArgs("Encrypt")}}.
		Execute(core.NewDish([]byte(input), core.TypeString))
	if err != nil {
		t.Fatalf("encrypt: %v", err)
	}
	pt, err := core.Recipe{{Op: "SIGABA", Args: sigabaDefaultArgs("Decrypt")}}.Execute(ct)
	if err != nil {
		t.Fatalf("decrypt: %v", err)
	}
	if pt.String() != input {
		t.Fatalf("round trip: got %q, want %q", pt.String(), input)
	}
}

// TestSigabaIndexOf directly exercises the helper's found and not-found paths
// (the not-found path is unreachable through Run, where every mapping is a
// permutation, but the helper is written defensively).
func TestSigabaIndexOf(t *testing.T) {
	s := []int{3, 1, 2}
	if got := sigabaIndexOf(s, 2); got != 2 {
		t.Fatalf("found: got %d, want 2", got)
	}
	if got := sigabaIndexOf(s, 9); got != -1 {
		t.Fatalf("not found: got %d, want -1", got)
	}
}

// TestSIGABAFixtures transcribes the cases from
// CyberChef's tests/operations/tests/SIGABA.mjs.
func TestSIGABAFixtures(t *testing.T) {
	runCases(t, []opCase{
		{
			"SIGABA: encrypt test 1",
			"HELLO WORLD TESTING THE SIGABA MACHINE",
			"ULBECJCZJBJFVUDWAVRGRBMPSQHOTTNVQEESKN",
			sigabaRecipe(
				"BHKWECJDOVAYLFMITUGXRNSPZQ", true, "G",
				"CDTAKGQOZXLVJYHSWMIBPRUNEF", false, "L",
				"WAXHJZMBVDPOLTUYRCQFNSGKEI", false, "I",
				"HUSCWIMJQXDALVGBFTOYZKRPNE", false, "T",
				"RTLSMNKXFVWQUZGCHEJBYDAIPO", false, "B",
				"GHAQBRJWDMNZTSKLOUXYPFIECV", false, "N",
				"VFLGEMTCXZIQDYAKRPBONHWSUJ", true, "Q",
				"ZQCAYHRJNXPFLKIOTBUSVWMGDE", false, "B",
				"EZVSWPCTULGAOFDJNBIYMXKQHR", false, "J",
				"ELKSGDXMVYJUZNCAROQBPWHITF", false, "R",
				"3891625740", "3",
				"6297135408", "1",
				"2389715064", "8",
				"9264351708", "6",
				"9573086142", "6",
				"Encrypt",
			),
		},
		{
			"SIGABA: encrypt test 2",
			"PCRPJZWSPNOHMWANBFBEIVZOXDQESPYDEFBNTHXLSICIRPKUATJVDUQFLZOKGHHHDUDIBRKUHVCGAGLBWVGFFXNDHKPFSPSCIIPCXUFRRHNYWIJFEJWQSGMSNJHWSLPKVXHUQUWIURHDIHIUTWGQFIYLTKEZAUESWYEKIWXUSSXWXBEHCXCUDQWKCISVPKXJVPOIJZWTUGKAORBMKBAQUZOPTSUSYZRROWQUYKNCLHVIHEGWCCONGVHEKCEXVYIPNILIXTXDELNGLJGMEQKKQJWZLPNXPOGIOSVAEAJYKWYJXXGKKPLVYAZGDCMNHMPLCYWDQSRBEMVVVZVFYJMRYGHJOTDOEQVRQOVXOGOVYGTXETFHAYELRYVDGWOFVGAOWPMHQYRZMNXVTAHWSKZLJDFVQPZGMHZWFNOBHSZHEDAEXIFCEEJYZDOEFOQWCXTKPJRUEITKHVCITCLKBUFNAFBYXELAYPBRGGGOCCAGLXXJXTSWCJHMHQPVUIBAGBDKAGEEEPKRGGICJQXSYHBNNAKGYODRAUWAEYHWCKHEQIBAONWQJYQCIFKDTOCTJMBJULWKMSNNMPXINHZQWUMJQLQKIPVZVRGYPCJJZMENWTFTUSPCSPRXHMZPCHCNQTUDCOUJHRKYQIUWWVEVVRYFDIYRQISNGPMQLNMCNMVBEWHNCUODHAGEVEUMKVZLEIKYAMPGVVSBYNRJMFCATDXTQCYXIBCXXKYEYHHYERQGQWZTWCEJBFQLRFFCIVVSZUKGLOTLNGLQNTIKTBBWVFMONUFKRLCJASEKUEEDDQDIVQMFRSJRNHYZJODFHSCJSDAIRUXOSDNFUFUFMNZYQIEGRUXKUPCHENUEZHRKYHDRJYSHLZNYRBWVXORMJMJRIRNSAJQRUMPCXUDFYRGKEAXQXJHPEWNIYIDURDGWIFEMSOFYYCFRZGMZXJNTLTJBBSZIULQSOMEVGCTCVXUHTIEHSPOPQYCJLPAJAPQPAQXE",
			"GMEXPPCMFGKUVGXZHVTCKXRSTJUYWNOKFVELWAHHSJBXGOEXCMLOVSIMCDMGEYMWWTFDUMCDUJEZITNPVVBGQDJEVHJXSKJAAUZWBELMSPUTXCUYPDTJCQXEBGWPWRSQLSNFMASCTJZDSFNKDDTAXLRGUPKCBNXMZPADJSFGGNYKRPYBNTYPTGVPACBEINILNACWFVKMJPGCEZFROEYYKTGYSQYMFSGVDOJJONNYEYSCCIXWLKUSJZDRVAQSNUWHMDJVDNNMPGOYRGQRSBGSPQKGCTFZQWSOXBWSQZDCRQJQAWZDPQEILGMMABIMCDPNSKAFCLPQGIRJCMGQREBEUHBYREXFABFMVZTZBDUMASVNUMHIYRSZLGNZFMVAIABLCUZLJLKKZPWEXDHYZFVSNRLCLNDRKLKSWRHQVQJRTHCNFZXDEXSLAXXOGMFVSGCJGAWOLGDMTLWSFNTCUVCCEACINRZAZZOGLEHHXLPHVKILBBJDPOOCILQKKGODSXOBDPZZDXHJLLBOBVFCHJVMUBUZZIKGCWGCYGXVEHHIJGPEQERWEZLILQNHPHALFKFMGADNELGBKILKIUETGDCBQUEOECWVFNOXTJKUYPWBNEKYSIKMVSAMBZGLIKDAOELRSTKFASEKABTUCPSFEGXXQGDFPSPVOLBHGLZSLLWCABSRKZDQQRKVCKXDGTIHPDNMPDZEXYFYKXZTPJPLYOFNLWAGKJEOHOYLMZELXIDWWNXPKEPUCKNNNHJLFYHPQNHMMCGMUPHSUSYYIVWTIMFKKKTFPGFTLTWWSQBRBMGBTZXPVULKNZIIKVTYLJFISGPTLZFTCLGNZOMVKZOIMUDGXRDDSVFRHRYWBEWHYLCUISYMRWAZZAQPJYXZQQKZLILOSHXUTQJFPTXQSREKSUDZTLGUDLUGOJMQHJRJHXCHQTKJULTWWQOXIRFRQEYBPJPEKXFIRMNATWNFBADOSIJVZYRYDBHDAEDJUVDHLDAU",
			sigabaRecipe(
				"YCHLQSUGBDIXNZKERPVJTAWFOM", true, "A",
				"INPXBWETGUYSAOCHVLDMQKZJFR", false, "B",
				"WNDRIOZPTAXHFJYQBMSVEKUCGL", false, "C",
				"TZGHOBKRVUXLQDMPNFWCJYEIAS", false, "D",
				"YWTAHRQJVLCEXUNGBIPZMSDFOK", true, "E",
				"QSLRBTEKOGAICFWYVMHJNXZUDP", false, "F",
				"CHJDQIGNBSAKVTUOXFWLEPRMZY", false, "G",
				"CDFAJXTIMNBEQHSUGRYLWZKVPO", true, "H",
				"XHFESZDNRBCGKQIJLTVMUOYAPW", false, "I",
				"EZJQXMOGYTCSFRIUPVNADLHWBK", false, "J",
				"7591482630", "0",
				"3810592764", "1",
				"4086153297", "2",
				"3980526174", "3",
				"6497135280", "4",
				"Encrypt",
			),
		},
		{
			"SIGABA: decrypt test",
			"AKDHFWAYSLHJDKXEVMJJHGKFTQBZPJPJILOVHMBYOAGBZVLLTQUOIKXFPUFNILBDPCAELMAPSXTLMUEGSDTNUDWGZDADBFELWWHKVPRZNDATDPYEHIDMTGAGPDEZYXFSASVKSBMXVOJQXRMHDBWUNZDTIIIVKHJYPIEUHAJCNBXNLGVFADEWIKXDJZBUTGOQBCQZWYKRVEENWRWWRYDNOAPGMODTPTUJZCLUCRDILJABNTBTWUEIJSJRQBUVCOUJJDWFMNNUHXBDFYXLGUMXQEAWSVHBXQGEOOGPYRVOAJLAIYIOHHEXACDTAWWCBGQRNPERSIKHTXPXKBUNACZLFZTRBMBBDDGKNBIQMFHZROCZZBGNZSJKDRRWPEQHLCFADNPWPWSLPIFNKBWQPMARUERGWUUODXSCOJQECGHIZRFRNRSXWSFWKISHHTUFRVXLHCQWGBMRDHCYDSVNIDDRSTODCGJSSBLUYOBGEWFOVKOZBJTYCAKMZECUGLJGTSZJNBOLTMUZRRSIGGRQHLRPMGLINASSMZOBNACKUMSFNIZAUFCPFXXOOTJQWWLZOFLGZLHJCWZJCRJKVOUDLNMKQATGVTOFHACAEKFLRWRTTMVRXHYGOTYPNBMUSKDAKXFCICUOVSWXGPQOYUUWTWRPQMEQCSDJMMJKELIHGEDYKWOVHVPUAIBFGAODXODXVFIIZIGWRZSBTIGXVHFABMMOPGVMLGHQQXNOEJRDLOBGUOWSELBHERZFSBLUODMOGIBNVGVGQYDBTKLOPNKZZNGLTTGZYYXIBAHZJDCILZXKNSJDHXWTYQLFHTUINTYSBPIXOPLOQHSAHGQPYUWYNPKMRBBBYIICCBBJRKWVLBIDBBEKJCXHLPUBMIGBUFYDPOCSRUNZOKMKJHMYFJZWFNHQZOGGRTNNUVLMRLDSAJIECTYCJKBYVNAXGCMGNVFJEDSATZQDQTYRBPLZKHAXMOVJZEDKINXKBUVWXXHTYUFO",
			"KTSOYDGMLPMVXEAJIATXCNQFXHBNCBXIJOCQGCQBRQSBYFOOEVPVXACBMIUIRNVMJHREKRHBSXJFSMWCKTTCYXJOFSJCQECXXCHTEGPEYSMYDHCSMODUAVBNLILYUIBBIXJCXXNQPCERRSMJTPQLMOXSKTRPWOFUSWXOYRJLBIJGIOYTEAEJEGGYAGSXNHNQTETANPWEGATHSBFLHCVHVIJUAKDVGQCWUSIFFFVAJYPJAFUYDXSLGPGESOUAYXBQIIOXWTXNOXLNCGWSUKVIBMOUGNHORYLSNVNNJLKKFDUAEISOLBLCXYHMDGVBVVVIKDLTMTDVWWJBXWXROVTJBXXKXLEWTTISKIUMYSACVUGGNANMCGUMFNQUXDLTHJNYTFIQEPKQQQSSROYJOILJYQXICXACWGOHCSHENXJILOMIIFCIOUDXDCINIVKIRJCVHWXSFQXMNRBJJWTPXNJADEOPEJBLKHKXNTORIRVRLXUXXAMKMODBXNLQCVJXVOTBRHXBBVJHPFEQFCRXYRRXHXPTXXSUESUTHUGOWQYQPQFPXQPVGEIRPQNKXXMBHIPECRUWFEWJUTYIKSMJSRQIQAIAMXTGDXSJIABHIGKUPJBCHWMVYTMQNQYGDHCNMBSVTPXNFRELFXXQYIOLCDEXDXDVSINICOXRMNSPICPQMOBIDJCNBJKXFAVMUXOXHERJIBIXLMXXULDXKXXHAQDXEXIWXOEEUGKSUGCMRWJDPYCYKXTPCOXMURAJCPRXKFJAJALERWRHVMFHOGMFHXGSXQDPJCJNXRQFGHKRCYTEBJDHPCMYFEAPWSVVMMBVUJJMCAAYURHUPVQVJYDCSNMQEMNIFEXYXIIXBVRVILXAUCBDXRJHGPKPYXHPPPNVSBBCDRLVVIYPKAKYIXTJVYDGVPHXULWMADBEICNIFKWUOOHEFNANDKOXMCVBVORLQYNXLULOEGVGWNKNMOHYVRSYSOVYGAKCGAWKGAIAQNQR",
			sigabaRecipe(
				"YCHLQSUGBDIXNZKERPVJTAWFOM", true, "A",
				"INPXBWETGUYSAOCHVLDMQKZJFR", false, "B",
				"WNDRIOZPTAXHFJYQBMSVEKUCGL", false, "C",
				"TZGHOBKRVUXLQDMPNFWCJYEIAS", false, "D",
				"YWTAHRQJVLCEXUNGBIPZMSDFOK", true, "E",
				"QSLRBTEKOGAICFWYVMHJNXZUDP", false, "F",
				"CHJDQIGNBSAKVTUOXFWLEPRMZY", false, "G",
				"CDFAJXTIMNBEQHSUGRYLWZKVPO", true, "H",
				"XHFESZDNRBCGKQIJLTVMUOYAPW", false, "I",
				"EZJQXMOGYTCSFRIUPVNADLHWBK", false, "J",
				"7591482630", "0",
				"3810592764", "1",
				"4086153297", "2",
				"3980526174", "3",
				"6497135280", "4",
				"Decrypt",
			),
		},
	})
}
