package codepage

import (
	"encoding/hex"
	"encoding/json"
	"os"
	"slices"
	"testing"
)

// codepageVectors is the oracle data generated by tools/cpgen/gen_vectors.js
// from cptable (the library CyberChef wraps).
type codepageVectors struct {
	EncInputs []string `json:"encInputs"`
	DecInputs []string `json:"decInputs"`
	RtStrings []string `json:"rtStrings"`
	Cps       []struct {
		Cp    int       `json:"cp"`
		Name  string    `json:"name"`
		Magic string    `json:"magic"`
		Enc   []*string `json:"enc"`
		Dec   []*string `json:"dec"`
		Rt    []struct {
			S    string  `json:"s"`
			H    *string `json:"h"`
			Back *string `json:"back"`
		} `json:"rt"`
	} `json:"cps"`
}

func loadCodepageVectors(t *testing.T) codepageVectors {
	t.Helper()
	b, err := os.ReadFile("testdata/codepage_vectors.json")
	if err != nil {
		t.Fatalf("read vectors: %v", err)
	}
	var v codepageVectors
	if err := json.Unmarshal(b, &v); err != nil {
		t.Fatalf("parse vectors: %v", err)
	}
	return v
}

// TestCodepageEngineDifferential verifies Encode/Decode reproduce
// cptable byte-for-byte across all 152 CyberChef charsets.
func TestCodepageEngineDifferential(t *testing.T) {
	v := loadCodepageVectors(t)
	for _, c := range v.Cps {
		t.Run(c.Name, func(t *testing.T) {
			for i, in := range v.EncInputs {
				got, err := Encode(c.Cp, in)
				want := c.Enc[i]
				if want == nil {
					if err == nil {
						t.Errorf("encode(%q): expected error, got %x", in, got)
					}
					continue
				}
				if err != nil {
					t.Errorf("encode(%q): unexpected error %v (want %s)", in, err, *want)
					continue
				}
				if hex.EncodeToString(got) != *want {
					t.Errorf("encode(%q): got %x, want %s", in, got, *want)
				}
			}
			for i, h := range v.DecInputs {
				data, _ := hex.DecodeString(h)
				got, err := Decode(c.Cp, data)
				want := c.Dec[i]
				if want == nil {
					if err == nil {
						t.Errorf("decode(%s): expected error, got %q", h, got)
					}
					continue
				}
				if err != nil {
					t.Errorf("decode(%s): unexpected error %v", h, err)
					continue
				}
				if got != *want {
					t.Errorf("decode(%s): got %q, want %q", h, got, *want)
				}
			}
			for _, rt := range c.Rt {
				got, err := Encode(c.Cp, rt.S)
				if rt.H == nil {
					if err == nil {
						t.Errorf("rt encode(%q): expected error", rt.S)
					}
					continue
				}
				if err != nil || hex.EncodeToString(got) != *rt.H {
					t.Errorf("rt encode(%q): got %x/%v, want %s", rt.S, got, err, *rt.H)
					continue
				}
				back, derr := Decode(c.Cp, got)
				if rt.Back == nil {
					if derr == nil {
						t.Errorf("rt decode(%q): expected error", rt.S)
					}
					continue
				}
				if derr != nil || back != *rt.Back {
					t.Errorf("rt decode(%s): got %q/%v, want %q", *rt.H, back, derr, *rt.Back)
				}
			}
		})
	}
}

// --- direct tests for the per-encoding decoders extracted from magicDecode ---

// TestDecodeASCII documents byte→code-unit passthrough.
func TestDecodeASCII(t *testing.T) {
	if got := decodeASCII([]byte{0x41, 0x80}); !slices.Equal(got, []uint16{0x41, 0x80}) {
		t.Fatalf("decodeASCII = %v", got)
	}
}

// TestDecodeUTF8 documents 1/2/3-byte sequences and BOM stripping.
func TestDecodeUTF8(t *testing.T) {
	cases := []struct {
		name string
		in   []byte
		want []uint16
	}{
		{"ascii", []byte{0x41}, []uint16{0x41}},
		{"two-byte é", []byte{0xC3, 0xA9}, []uint16{0xE9}},
		{"three-byte €", []byte{0xE2, 0x82, 0xAC}, []uint16{0x20AC}},
		{"BOM stripped", []byte{0xEF, 0xBB, 0xBF, 0x41}, []uint16{0x41}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := decodeUTF8(c.in); !slices.Equal(got, c.want) {
				t.Fatalf("decodeUTF8(%x) = %v, want %v", c.in, got, c.want)
			}
		})
	}
}

// TestDecodeUTF16 documents both byte orders and their BOMs.
func TestDecodeUTF16(t *testing.T) {
	if got := decodeUTF16([]byte{0x41, 0x00}, true); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("LE = %v", got)
	}
	if got := decodeUTF16([]byte{0xFF, 0xFE, 0x41, 0x00}, true); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("LE BOM = %v", got)
	}
	if got := decodeUTF16([]byte{0x00, 0x41}, false); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("BE = %v", got)
	}
	if got := decodeUTF16([]byte{0xFE, 0xFF, 0x00, 0x41}, false); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("BE BOM = %v", got)
	}
}

// TestDecodeUTF32 documents both byte orders (little-endian BOM, big-endian
// short-trailing-byte handling).
func TestDecodeUTF32(t *testing.T) {
	if got := decodeUTF32LE([]byte{0x41, 0, 0, 0}); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("LE = %v", got)
	}
	if got := decodeUTF32LE([]byte{0xFF, 0xFE, 0, 0, 0x41, 0, 0, 0}); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("LE BOM = %v", got)
	}
	if got := decodeUTF32BE([]byte{0, 0, 0, 0x41}); !slices.Equal(got, []uint16{0x41}) {
		t.Fatalf("BE = %v", got)
	}
}

// --- direct tests for the per-encoding encoders extracted from magicEncode ---

// TestEncodeASCII documents low-byte passthrough.
func TestEncodeASCII(t *testing.T) {
	if got := encodeASCII([]uint16{0x41, 0x80}); !slices.Equal(got, []byte{0x41, 0x80}) {
		t.Fatalf("encodeASCII = %v", got)
	}
}

// TestEncodeUTF8 documents 1/2/3-byte sequences.
func TestEncodeUTF8(t *testing.T) {
	cases := []struct {
		name string
		in   []uint16
		want []byte
	}{
		{"ascii", []uint16{0x41}, []byte{0x41}},
		{"two-byte é", []uint16{0xE9}, []byte{0xC3, 0xA9}},
		{"three-byte €", []uint16{0x20AC}, []byte{0xE2, 0x82, 0xAC}},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := encodeUTF8(c.in); !slices.Equal(got, c.want) {
				t.Fatalf("encodeUTF8(%x) = %x, want %x", c.in, got, c.want)
			}
		})
	}
}

// TestEncodeUTF16 documents both byte orders.
func TestEncodeUTF16(t *testing.T) {
	if got := encodeUTF16([]uint16{0x0041}, true); !slices.Equal(got, []byte{0x41, 0x00}) {
		t.Fatalf("LE = %x", got)
	}
	if got := encodeUTF16([]uint16{0x0041}, false); !slices.Equal(got, []byte{0x00, 0x41}) {
		t.Fatalf("BE = %x", got)
	}
}

// TestEncodeUTF32 documents both byte orders.
func TestEncodeUTF32(t *testing.T) {
	if got := encodeUTF32([]uint16{0x0041}, true); !slices.Equal(got, []byte{0x41, 0, 0, 0}) {
		t.Fatalf("LE = %x", got)
	}
	if got := encodeUTF32([]uint16{0x0041}, false); !slices.Equal(got, []byte{0, 0, 0, 0x41}) {
		t.Fatalf("BE = %x", got)
	}
}

// --- direct tests for the helpers extracted from utf7Decode ---

// TestUTF7SkipBOM documents skipping the optional UTF-7 BOM ("+/v8-" or "+/v…").
func TestUTF7SkipBOM(t *testing.T) {
	if got := utf7SkipBOM([]byte{0x41}); got != 0 { // no BOM
		t.Fatalf("no BOM = %d", got)
	}
	if got := utf7SkipBOM([]byte{0x2b, 0x2f, 0x76, 0x38, 0x2d}); got != 5 { // "+/v8-"
		t.Fatalf("full BOM = %d", got)
	}
	if got := utf7SkipBOM([]byte{0x2b, 0x2f, 0x76, 0x38, 0x41}); got != 4 { // "+/v8" + data
		t.Fatalf("short BOM = %d", got)
	}
}

// TestUTF7DecodeBase64Run documents decoding a modified-base64 run into its
// UTF-16BE bytes: "+AGk-" carries the two bytes 0x00 0x69 (the letter 'i').
func TestUTF7DecodeBase64Run(t *testing.T) {
	got := utf7DecodeBase64Run([]byte("+AGk-"), 0, 5, 1)
	if !slices.Equal(got, []byte{0x00, 0x69}) {
		t.Fatalf("utf7DecodeBase64Run = %v, want [0 105]", got)
	}
}
